// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_personas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIPersona = `-- name: CreateAIPersona :one
INSERT INTO facebook.ai_personas (name, description, system_prompt, few_shot_examples, post_processor_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, system_prompt, few_shot_examples, post_processor_type, created_at, updated_at
`

type CreateAIPersonaParams struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	SystemPrompt      string  `json:"system_prompt"`
	FewShotExamples   *string `json:"few_shot_examples"`
	PostProcessorType string  `json:"post_processor_type"`
}

func (q *Queries) CreateAIPersona(ctx context.Context, arg CreateAIPersonaParams) (FacebookAiPersona, error) {
	row := q.db.QueryRow(ctx, createAIPersona,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.FewShotExamples,
		arg.PostProcessorType,
	)
	var i FacebookAiPersona
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.FewShotExamples,
		&i.PostProcessorType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAIPersona = `-- name: DeleteAIPersona :exec
DELETE FROM facebook.ai_personas WHERE id = $1
`

func (q *Queries) DeleteAIPersona(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIPersona, id)
	return err
}

const getAIPersona = `-- name: GetAIPersona :one
SELECT id, name, description, system_prompt, few_shot_examples, post_processor_type, created_at, updated_at
FROM facebook.ai_personas
WHERE id = $1
`

func (q *Queries) GetAIPersona(ctx context.Context, id pgtype.UUID) (FacebookAiPersona, error) {
	row := q.db.QueryRow(ctx, getAIPersona, id)
	var i FacebookAiPersona
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.FewShotExamples,
		&i.PostProcessorType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIPersonas = `-- name: ListAIPersonas :many
SELECT id, name, description, system_prompt, few_shot_examples, post_processor_type, created_at, updated_at
FROM facebook.ai_personas
ORDER BY updated_at DESC
`

func (q *Queries) ListAIPersonas(ctx context.Context) ([]FacebookAiPersona, error) {
	rows, err := q.db.Query(ctx, listAIPersonas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookAiPersona{}
	for rows.Next() {
		var i FacebookAiPersona
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.FewShotExamples,
			&i.PostProcessorType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIPersona = `-- name: UpdateAIPersona :one
UPDATE facebook.ai_personas
SET name = $2,
    description = $3,
    system_prompt = $4,
    few_shot_examples = $5,
    post_processor_type = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, system_prompt, few_shot_examples, post_processor_type, created_at, updated_at
`

type UpdateAIPersonaParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Description       *string     `json:"description"`
	SystemPrompt      string      `json:"system_prompt"`
	FewShotExamples   *string     `json:"few_shot_examples"`
	PostProcessorType string      `json:"post_processor_type"`
}

func (q *Queries) UpdateAIPersona(ctx context.Context, arg UpdateAIPersonaParams) (FacebookAiPersona, error) {
	row := q.db.QueryRow(ctx, updateAIPersona,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.FewShotExamples,
		arg.PostProcessorType,
	)
	var i FacebookAiPersona
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.FewShotExamples,
		&i.PostProcessorType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePageAIPersona = `-- name: UpdatePageAIPersona :one
UPDATE facebook.pages
SET ai_persona_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type UpdatePageAIPersonaParams struct {
	ID          pgtype.UUID `json:"id"`
	AiPersonaID pgtype.UUID `json:"ai_persona_id"`
}

func (q *Queries) UpdatePageAIPersona(ctx context.Context, arg UpdatePageAIPersonaParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, updatePageAIPersona, arg.ID, arg.AiPersonaID)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}
