// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsSeries = `-- name: AnalyticsSeries :many
SELECT
  DATE(published_at) AS date,
  COUNT(*) AS posts,
  COALESCE(SUM(likes), 0) AS likes,
  COALESCE(SUM(comments), 0) AS comments,
  COALESCE(SUM(shares), 0) AS shares
FROM facebook.post_history
WHERE published_at >= $1 AND published_at < $2
GROUP BY DATE(published_at)
ORDER BY DATE(published_at)
`

type AnalyticsSeriesParams struct {
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	PublishedAt_2 pgtype.Timestamptz `json:"published_at_2"`
}

type AnalyticsSeriesRow struct {
	Date     pgtype.Date `json:"date"`
	Posts    int64       `json:"posts"`
	Likes    interface{} `json:"likes"`
	Comments interface{} `json:"comments"`
	Shares   interface{} `json:"shares"`
}

// Daily breakdown for chart rendering.
func (q *Queries) AnalyticsSeries(ctx context.Context, arg AnalyticsSeriesParams) ([]AnalyticsSeriesRow, error) {
	rows, err := q.db.Query(ctx, analyticsSeries, arg.PublishedAt, arg.PublishedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSeriesRow{}
	for rows.Next() {
		var i AnalyticsSeriesRow
		if err := rows.Scan(
			&i.Date,
			&i.Posts,
			&i.Likes,
			&i.Comments,
			&i.Shares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsSummary = `-- name: AnalyticsSummary :one
SELECT
  COALESCE(COUNT(*), 0) AS total_posts,
  COALESCE(SUM(likes), 0) AS total_likes,
  COALESCE(SUM(comments), 0) AS total_comments,
  COALESCE(SUM(shares), 0) AS total_shares,
  COALESCE(SUM(reach), 0) AS total_reach
FROM facebook.post_history
WHERE published_at >= $1 AND published_at < $2
`

type AnalyticsSummaryParams struct {
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	PublishedAt_2 pgtype.Timestamptz `json:"published_at_2"`
}

type AnalyticsSummaryRow struct {
	TotalPosts    interface{} `json:"total_posts"`
	TotalLikes    interface{} `json:"total_likes"`
	TotalComments interface{} `json:"total_comments"`
	TotalShares   interface{} `json:"total_shares"`
	TotalReach    interface{} `json:"total_reach"`
}

// Aggregates metrics over a date range (inclusive start, exclusive end).
func (q *Queries) AnalyticsSummary(ctx context.Context, arg AnalyticsSummaryParams) (AnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, analyticsSummary, arg.PublishedAt, arg.PublishedAt_2)
	var i AnalyticsSummaryRow
	err := row.Scan(
		&i.TotalPosts,
		&i.TotalLikes,
		&i.TotalComments,
		&i.TotalShares,
		&i.TotalReach,
	)
	return i, err
}

const dailyStats = `-- name: DailyStats :many
WITH days AS (
  SELECT generate_series(
    CURRENT_DATE - ($1 - 1) * INTERVAL '1 day',
    CURRENT_DATE,
    INTERVAL '1 day'
  )::date AS date
)
SELECT
  d.date,
  COALESCE(COUNT(ph.id), 0)::int AS posts_published,
  COALESCE(SUM(ph.likes), 0)::int AS total_likes,
  COALESCE(SUM(ph.comments), 0)::int AS total_comments,
  COALESCE(SUM(ph.shares), 0)::int AS total_shares
FROM days d
LEFT JOIN facebook.post_history ph ON DATE(ph.published_at) = d.date
GROUP BY d.date
ORDER BY d.date
`

type DailyStatsRow struct {
	Date           pgtype.Date `json:"date"`
	PostsPublished int32       `json:"posts_published"`
	TotalLikes     int32       `json:"total_likes"`
	TotalComments  int32       `json:"total_comments"`
	TotalShares    int32       `json:"total_shares"`
}

// Recent N days of daily stats (used by the dashboard summary).
func (q *Queries) DailyStats(ctx context.Context, dollar_1 interface{}) ([]DailyStatsRow, error) {
	rows, err := q.db.Query(ctx, dailyStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStatsRow{}
	for rows.Next() {
		var i DailyStatsRow
		if err := rows.Scan(
			&i.Date,
			&i.PostsPublished,
			&i.TotalLikes,
			&i.TotalComments,
			&i.TotalShares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
