// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brain_feed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBrainDrafts = `-- name: CountBrainDrafts :one
SELECT COUNT(*)::bigint
FROM facebook.brain_drafts
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountBrainDrafts(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countBrainDrafts, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countBrainFeeds = `-- name: CountBrainFeeds :one
SELECT COUNT(*)::bigint
FROM facebook.brain_feeds
WHERE
  ($1::text = '' OR page_id = $1)
  AND ($2::timestamptz IS NULL OR posted_at >= $2)
  AND ($3::timestamptz IS NULL OR posted_at <= $3)
  AND ($4::text = '' OR status = $4)
  AND ($5::text = '' OR content ILIKE '%' || $5 || '%')
`

type CountBrainFeedsParams struct {
	SourcePage   string             `json:"source_page"`
	FromT        pgtype.Timestamptz `json:"from_t"`
	ToT          pgtype.Timestamptz `json:"to_t"`
	StatusFilter string             `json:"status_filter"`
	SearchQ      string             `json:"search_q"`
}

func (q *Queries) CountBrainFeeds(ctx context.Context, arg CountBrainFeedsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBrainFeeds,
		arg.SourcePage,
		arg.FromT,
		arg.ToT,
		arg.StatusFilter,
		arg.SearchQ,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteBrainFeed = `-- name: DeleteBrainFeed :exec
DELETE FROM facebook.brain_feeds WHERE id = $1
`

func (q *Queries) DeleteBrainFeed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBrainFeed, id)
	return err
}

const getBrainFeedByCrawledPostID = `-- name: GetBrainFeedByCrawledPostID :one
SELECT id, crawled_post_id, page_id, page_name, content, media_urls, video_urls,
       thumbnail_urls, full_picture, media_type, likes, comments, shares,
       posted_at, source_url, permalink, brain_content_id, ingested_at,
       error_message, status, retry_count, created_at, updated_at
FROM facebook.brain_feeds
WHERE crawled_post_id = $1
`

func (q *Queries) GetBrainFeedByCrawledPostID(ctx context.Context, crawledPostID string) (FacebookBrainFeed, error) {
	row := q.db.QueryRow(ctx, getBrainFeedByCrawledPostID, crawledPostID)
	var i FacebookBrainFeed
	err := row.Scan(
		&i.ID,
		&i.CrawledPostID,
		&i.PageID,
		&i.PageName,
		&i.Content,
		&i.MediaUrls,
		&i.VideoUrls,
		&i.ThumbnailUrls,
		&i.FullPicture,
		&i.MediaType,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.PostedAt,
		&i.SourceUrl,
		&i.Permalink,
		&i.BrainContentID,
		&i.IngestedAt,
		&i.ErrorMessage,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrainFeedByID = `-- name: GetBrainFeedByID :one
SELECT id, crawled_post_id, page_id, page_name, content, media_urls, video_urls,
       thumbnail_urls, full_picture, media_type, likes, comments, shares,
       posted_at, source_url, permalink, brain_content_id, ingested_at,
       error_message, status, retry_count, created_at, updated_at
FROM facebook.brain_feeds
WHERE id = $1
`

func (q *Queries) GetBrainFeedByID(ctx context.Context, id pgtype.UUID) (FacebookBrainFeed, error) {
	row := q.db.QueryRow(ctx, getBrainFeedByID, id)
	var i FacebookBrainFeed
	err := row.Scan(
		&i.ID,
		&i.CrawledPostID,
		&i.PageID,
		&i.PageName,
		&i.Content,
		&i.MediaUrls,
		&i.VideoUrls,
		&i.ThumbnailUrls,
		&i.FullPicture,
		&i.MediaType,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.PostedAt,
		&i.SourceUrl,
		&i.Permalink,
		&i.BrainContentID,
		&i.IngestedAt,
		&i.ErrorMessage,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBrainDraft = `-- name: InsertBrainDraft :one
INSERT INTO facebook.brain_drafts (
  feed_id, content, provenance_id, validation_status, validation_details,
  warnings, persona_id, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, feed_id, content, provenance_id, validation_status, validation_details,
          warnings, persona_id, kanban_job_id, status, created_at, updated_at
`

type InsertBrainDraftParams struct {
	FeedID            pgtype.UUID `json:"feed_id"`
	Content           string      `json:"content"`
	ProvenanceID      string      `json:"provenance_id"`
	ValidationStatus  string      `json:"validation_status"`
	ValidationDetails []byte      `json:"validation_details"`
	Warnings          []byte      `json:"warnings"`
	PersonaID         string      `json:"persona_id"`
	Status            string      `json:"status"`
}

type InsertBrainDraftRow struct {
	ID                pgtype.UUID        `json:"id"`
	FeedID            pgtype.UUID        `json:"feed_id"`
	Content           string             `json:"content"`
	ProvenanceID      string             `json:"provenance_id"`
	ValidationStatus  string             `json:"validation_status"`
	ValidationDetails []byte             `json:"validation_details"`
	Warnings          []byte             `json:"warnings"`
	PersonaID         string             `json:"persona_id"`
	KanbanJobID       *string            `json:"kanban_job_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertBrainDraft(ctx context.Context, arg InsertBrainDraftParams) (InsertBrainDraftRow, error) {
	row := q.db.QueryRow(ctx, insertBrainDraft,
		arg.FeedID,
		arg.Content,
		arg.ProvenanceID,
		arg.ValidationStatus,
		arg.ValidationDetails,
		arg.Warnings,
		arg.PersonaID,
		arg.Status,
	)
	var i InsertBrainDraftRow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Content,
		&i.ProvenanceID,
		&i.ValidationStatus,
		&i.ValidationDetails,
		&i.Warnings,
		&i.PersonaID,
		&i.KanbanJobID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBrainFeed = `-- name: InsertBrainFeed :one
INSERT INTO facebook.brain_feeds (
  crawled_post_id, page_id, page_name, content, media_urls, video_urls,
  thumbnail_urls, full_picture, media_type, likes, comments, shares,
  posted_at, source_url, permalink, status
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16
)
ON CONFLICT (crawled_post_id) DO UPDATE SET updated_at = NOW()
RETURNING id, crawled_post_id, page_id, page_name, content, media_urls, video_urls,
          thumbnail_urls, full_picture, media_type, likes, comments, shares,
          posted_at, source_url, permalink, brain_content_id, ingested_at,
          error_message, status, retry_count, created_at, updated_at
`

type InsertBrainFeedParams struct {
	CrawledPostID string             `json:"crawled_post_id"`
	PageID        string             `json:"page_id"`
	PageName      *string            `json:"page_name"`
	Content       string             `json:"content"`
	MediaUrls     []byte             `json:"media_urls"`
	VideoUrls     []byte             `json:"video_urls"`
	ThumbnailUrls []byte             `json:"thumbnail_urls"`
	FullPicture   *string            `json:"full_picture"`
	MediaType     string             `json:"media_type"`
	Likes         int32              `json:"likes"`
	Comments      int32              `json:"comments"`
	Shares        int32              `json:"shares"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	SourceUrl     string             `json:"source_url"`
	Permalink     string             `json:"permalink"`
	Status        string             `json:"status"`
}

func (q *Queries) InsertBrainFeed(ctx context.Context, arg InsertBrainFeedParams) (FacebookBrainFeed, error) {
	row := q.db.QueryRow(ctx, insertBrainFeed,
		arg.CrawledPostID,
		arg.PageID,
		arg.PageName,
		arg.Content,
		arg.MediaUrls,
		arg.VideoUrls,
		arg.ThumbnailUrls,
		arg.FullPicture,
		arg.MediaType,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.PostedAt,
		arg.SourceUrl,
		arg.Permalink,
		arg.Status,
	)
	var i FacebookBrainFeed
	err := row.Scan(
		&i.ID,
		&i.CrawledPostID,
		&i.PageID,
		&i.PageName,
		&i.Content,
		&i.MediaUrls,
		&i.VideoUrls,
		&i.ThumbnailUrls,
		&i.FullPicture,
		&i.MediaType,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.PostedAt,
		&i.SourceUrl,
		&i.Permalink,
		&i.BrainContentID,
		&i.IngestedAt,
		&i.ErrorMessage,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrainDraftsByFeedIDs = `-- name: ListBrainDraftsByFeedIDs :many
SELECT id, feed_id, content, provenance_id, validation_status, validation_details,
       warnings, persona_id, kanban_job_id, status, created_at, updated_at
FROM facebook.brain_drafts
WHERE feed_id = ANY($1::uuid[])
ORDER BY created_at DESC
`

type ListBrainDraftsByFeedIDsRow struct {
	ID                pgtype.UUID        `json:"id"`
	FeedID            pgtype.UUID        `json:"feed_id"`
	Content           string             `json:"content"`
	ProvenanceID      string             `json:"provenance_id"`
	ValidationStatus  string             `json:"validation_status"`
	ValidationDetails []byte             `json:"validation_details"`
	Warnings          []byte             `json:"warnings"`
	PersonaID         string             `json:"persona_id"`
	KanbanJobID       *string            `json:"kanban_job_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBrainDraftsByFeedIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListBrainDraftsByFeedIDsRow, error) {
	rows, err := q.db.Query(ctx, listBrainDraftsByFeedIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrainDraftsByFeedIDsRow{}
	for rows.Next() {
		var i ListBrainDraftsByFeedIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Content,
			&i.ProvenanceID,
			&i.ValidationStatus,
			&i.ValidationDetails,
			&i.Warnings,
			&i.PersonaID,
			&i.KanbanJobID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrainFeeds = `-- name: ListBrainFeeds :many
SELECT id, crawled_post_id, page_id, page_name, content, media_urls, video_urls,
       thumbnail_urls, full_picture, media_type, likes, comments, shares,
       posted_at, source_url, permalink, brain_content_id, ingested_at,
       error_message, status, retry_count, created_at, updated_at
FROM facebook.brain_feeds
WHERE
  ($1::text = '' OR page_id = $1)
  AND ($2::timestamptz IS NULL OR posted_at >= $2)
  AND ($3::timestamptz IS NULL OR posted_at <= $3)
  AND ($4::text = '' OR status = $4)
  AND ($5::text = '' OR content ILIKE '%' || $5 || '%')
ORDER BY posted_at DESC
LIMIT $7 OFFSET $6
`

type ListBrainFeedsParams struct {
	SourcePage   string             `json:"source_page"`
	FromT        pgtype.Timestamptz `json:"from_t"`
	ToT          pgtype.Timestamptz `json:"to_t"`
	StatusFilter string             `json:"status_filter"`
	SearchQ      string             `json:"search_q"`
	Off          int32              `json:"off"`
	PageSize     int32              `json:"page_size"`
}

func (q *Queries) ListBrainFeeds(ctx context.Context, arg ListBrainFeedsParams) ([]FacebookBrainFeed, error) {
	rows, err := q.db.Query(ctx, listBrainFeeds,
		arg.SourcePage,
		arg.FromT,
		arg.ToT,
		arg.StatusFilter,
		arg.SearchQ,
		arg.Off,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookBrainFeed{}
	for rows.Next() {
		var i FacebookBrainFeed
		if err := rows.Scan(
			&i.ID,
			&i.CrawledPostID,
			&i.PageID,
			&i.PageName,
			&i.Content,
			&i.MediaUrls,
			&i.VideoUrls,
			&i.ThumbnailUrls,
			&i.FullPicture,
			&i.MediaType,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.PostedAt,
			&i.SourceUrl,
			&i.Permalink,
			&i.BrainContentID,
			&i.IngestedAt,
			&i.ErrorMessage,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrainFeedsByIDs = `-- name: ListBrainFeedsByIDs :many
SELECT id, crawled_post_id, page_id, page_name, content, media_urls, video_urls,
       thumbnail_urls, full_picture, media_type, likes, comments, shares,
       posted_at, source_url, permalink, brain_content_id, ingested_at,
       error_message, status, retry_count, created_at, updated_at
FROM facebook.brain_feeds
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListBrainFeedsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]FacebookBrainFeed, error) {
	rows, err := q.db.Query(ctx, listBrainFeedsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookBrainFeed{}
	for rows.Next() {
		var i FacebookBrainFeed
		if err := rows.Scan(
			&i.ID,
			&i.CrawledPostID,
			&i.PageID,
			&i.PageName,
			&i.Content,
			&i.MediaUrls,
			&i.VideoUrls,
			&i.ThumbnailUrls,
			&i.FullPicture,
			&i.MediaType,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.PostedAt,
			&i.SourceUrl,
			&i.Permalink,
			&i.BrainContentID,
			&i.IngestedAt,
			&i.ErrorMessage,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrainDraftKanbanJob = `-- name: UpdateBrainDraftKanbanJob :exec
UPDATE facebook.brain_drafts
SET kanban_job_id = $2, status = 'pushed', updated_at = NOW()
WHERE id = $1
`

type UpdateBrainDraftKanbanJobParams struct {
	ID          pgtype.UUID `json:"id"`
	KanbanJobID *string     `json:"kanban_job_id"`
}

func (q *Queries) UpdateBrainDraftKanbanJob(ctx context.Context, arg UpdateBrainDraftKanbanJobParams) error {
	_, err := q.db.Exec(ctx, updateBrainDraftKanbanJob, arg.ID, arg.KanbanJobID)
	return err
}

const updateBrainFeedBrainID = `-- name: UpdateBrainFeedBrainID :exec
UPDATE facebook.brain_feeds
SET brain_content_id = $2, status = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateBrainFeedBrainIDParams struct {
	ID             pgtype.UUID `json:"id"`
	BrainContentID *string     `json:"brain_content_id"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdateBrainFeedBrainID(ctx context.Context, arg UpdateBrainFeedBrainIDParams) error {
	_, err := q.db.Exec(ctx, updateBrainFeedBrainID, arg.ID, arg.BrainContentID, arg.Status)
	return err
}

const updateBrainFeedStatus = `-- name: UpdateBrainFeedStatus :exec
UPDATE facebook.brain_feeds
SET status = $2, error_message = $3, retry_count = retry_count + 1, updated_at = NOW()
WHERE id = $1
`

type UpdateBrainFeedStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) UpdateBrainFeedStatus(ctx context.Context, arg UpdateBrainFeedStatusParams) error {
	_, err := q.db.Exec(ctx, updateBrainFeedStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
