// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimComment = `-- name: ClaimComment :one
SELECT facebook.claim_comment($1, $2) AS claimed
`

type ClaimCommentParams struct {
	PCommentID string `json:"p_comment_id"`
	PClaimedBy string `json:"p_claimed_by"`
}

func (q *Queries) ClaimComment(ctx context.Context, arg ClaimCommentParams) (bool, error) {
	row := q.db.QueryRow(ctx, claimComment, arg.PCommentID, arg.PClaimedBy)
	var claimed bool
	err := row.Scan(&claimed)
	return claimed, err
}

const getComment = `-- name: GetComment :one
SELECT
  id, post_id, page_id, from_id, from_name, message, created_time, like_count,
  reply_count, sentiment, intent, priority, is_hidden, is_liked,
  is_private_reply_sent, collected_info, received_at, claimed_at, claimed_by, processed
FROM facebook.comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id string) (FacebookComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i FacebookComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PageID,
		&i.FromID,
		&i.FromName,
		&i.Message,
		&i.CreatedTime,
		&i.LikeCount,
		&i.ReplyCount,
		&i.Sentiment,
		&i.Intent,
		&i.Priority,
		&i.IsHidden,
		&i.IsLiked,
		&i.IsPrivateReplySent,
		&i.CollectedInfo,
		&i.ReceivedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.Processed,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO facebook.comments (
  id, post_id, page_id, from_id, from_name, message, created_time, like_count,
  reply_count, sentiment, intent, priority, is_hidden, is_liked,
  is_private_reply_sent, collected_info, received_at, claimed_at, claimed_by, processed
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (id) DO UPDATE SET
  message = EXCLUDED.message,
  like_count = EXCLUDED.like_count,
  reply_count = EXCLUDED.reply_count,
  sentiment = EXCLUDED.sentiment,
  intent = EXCLUDED.intent,
  priority = EXCLUDED.priority,
  is_hidden = EXCLUDED.is_hidden,
  is_liked = EXCLUDED.is_liked,
  is_private_reply_sent = EXCLUDED.is_private_reply_sent,
  collected_info = EXCLUDED.collected_info,
  received_at = EXCLUDED.received_at,
  processed = EXCLUDED.processed
`

type InsertCommentParams struct {
	ID                 string             `json:"id"`
	PostID             string             `json:"post_id"`
	PageID             pgtype.UUID        `json:"page_id"`
	FromID             *string            `json:"from_id"`
	FromName           string             `json:"from_name"`
	Message            string             `json:"message"`
	CreatedTime        pgtype.Timestamptz `json:"created_time"`
	LikeCount          int32              `json:"like_count"`
	ReplyCount         int32              `json:"reply_count"`
	Sentiment          string             `json:"sentiment"`
	Intent             string             `json:"intent"`
	Priority           int32              `json:"priority"`
	IsHidden           bool               `json:"is_hidden"`
	IsLiked            bool               `json:"is_liked"`
	IsPrivateReplySent bool               `json:"is_private_reply_sent"`
	CollectedInfo      json.RawMessage    `json:"collected_info"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedAt          pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy          *string            `json:"claimed_by"`
	Processed          bool               `json:"processed"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.PostID,
		arg.PageID,
		arg.FromID,
		arg.FromName,
		arg.Message,
		arg.CreatedTime,
		arg.LikeCount,
		arg.ReplyCount,
		arg.Sentiment,
		arg.Intent,
		arg.Priority,
		arg.IsHidden,
		arg.IsLiked,
		arg.IsPrivateReplySent,
		arg.CollectedInfo,
		arg.ReceivedAt,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.Processed,
	)
	return err
}

const insertCommentReply = `-- name: InsertCommentReply :exec
INSERT INTO facebook.comment_replies (
  comment_id, reply_type, content, sent_by, status, facebook_reply_id, sent_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCommentReplyParams struct {
	CommentID       string             `json:"comment_id"`
	ReplyType       string             `json:"reply_type"`
	Content         string             `json:"content"`
	SentBy          string             `json:"sent_by"`
	Status          string             `json:"status"`
	FacebookReplyID *string            `json:"facebook_reply_id"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) InsertCommentReply(ctx context.Context, arg InsertCommentReplyParams) error {
	_, err := q.db.Exec(ctx, insertCommentReply,
		arg.CommentID,
		arg.ReplyType,
		arg.Content,
		arg.SentBy,
		arg.Status,
		arg.FacebookReplyID,
		arg.SentAt,
	)
	return err
}

const listCommentReplies = `-- name: ListCommentReplies :many
SELECT
  id, comment_id, reply_type, content, sent_by, status, facebook_reply_id, sent_at
FROM facebook.comment_replies
WHERE comment_id = $1
ORDER BY sent_at DESC
`

func (q *Queries) ListCommentReplies(ctx context.Context, commentID string) ([]FacebookCommentReply, error) {
	rows, err := q.db.Query(ctx, listCommentReplies, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookCommentReply{}
	for rows.Next() {
		var i FacebookCommentReply
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.ReplyType,
			&i.Content,
			&i.SentBy,
			&i.Status,
			&i.FacebookReplyID,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT
  id, post_id, page_id, from_id, from_name, message, created_time, like_count,
  reply_count, sentiment, intent, priority, is_hidden, is_liked,
  is_private_reply_sent, collected_info, received_at, claimed_at, claimed_by, processed
FROM facebook.comments
WHERE page_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListCommentsParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]FacebookComment, error) {
	rows, err := q.db.Query(ctx, listComments, arg.PageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookComment{}
	for rows.Next() {
		var i FacebookComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PageID,
			&i.FromID,
			&i.FromName,
			&i.Message,
			&i.CreatedTime,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Sentiment,
			&i.Intent,
			&i.Priority,
			&i.IsHidden,
			&i.IsLiked,
			&i.IsPrivateReplySent,
			&i.CollectedInfo,
			&i.ReceivedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedComments = `-- name: ListUnprocessedComments :many
SELECT
  id, post_id, page_id, from_id, from_name, message, created_time, like_count,
  reply_count, sentiment, intent, priority, is_hidden, is_liked,
  is_private_reply_sent, collected_info, received_at, claimed_at, claimed_by, processed
FROM facebook.comments
WHERE page_id = $1 AND processed = false
ORDER BY received_at ASC
LIMIT $2
`

type ListUnprocessedCommentsParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListUnprocessedComments(ctx context.Context, arg ListUnprocessedCommentsParams) ([]FacebookComment, error) {
	rows, err := q.db.Query(ctx, listUnprocessedComments, arg.PageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookComment{}
	for rows.Next() {
		var i FacebookComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PageID,
			&i.FromID,
			&i.FromName,
			&i.Message,
			&i.CreatedTime,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Sentiment,
			&i.Intent,
			&i.Priority,
			&i.IsHidden,
			&i.IsLiked,
			&i.IsPrivateReplySent,
			&i.CollectedInfo,
			&i.ReceivedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommentProcessed = `-- name: MarkCommentProcessed :exec
UPDATE facebook.comments
SET processed = true
WHERE id = $1
`

func (q *Queries) MarkCommentProcessed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markCommentProcessed, id)
	return err
}

const updateCommentLiked = `-- name: UpdateCommentLiked :exec
UPDATE facebook.comments
SET is_liked = $2,
    processed = true
WHERE id = $1
`

type UpdateCommentLikedParams struct {
	ID      string `json:"id"`
	IsLiked bool   `json:"is_liked"`
}

func (q *Queries) UpdateCommentLiked(ctx context.Context, arg UpdateCommentLikedParams) error {
	_, err := q.db.Exec(ctx, updateCommentLiked, arg.ID, arg.IsLiked)
	return err
}

const updateCommentPrivateReply = `-- name: UpdateCommentPrivateReply :exec
UPDATE facebook.comments
SET is_private_reply_sent = $2,
    processed = true
WHERE id = $1
`

type UpdateCommentPrivateReplyParams struct {
	ID                 string `json:"id"`
	IsPrivateReplySent bool   `json:"is_private_reply_sent"`
}

func (q *Queries) UpdateCommentPrivateReply(ctx context.Context, arg UpdateCommentPrivateReplyParams) error {
	_, err := q.db.Exec(ctx, updateCommentPrivateReply, arg.ID, arg.IsPrivateReplySent)
	return err
}
