// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT
  id, page_id, page_access_token, publish_mode, default_page_id,
  webhook_verify_token, app_secret,
  ai_model, auto_scheduling_enabled, auto_schedule_times, timezone,
  default_hashtags, enabled_content_tones, custom_content_tones,
  tone_description_overrides,
  kling_enabled, kling_prompt_template, kling_resolution,
  kling_aspect_ratio, kling_output_count, kling_schedule_days,
  kling_reference_page_url,
  kling_video_enabled, kling_video_prompts, kling_video_aspect_ratio,
  kling_video_output_count,
  created_at, updated_at
FROM facebook.config
WHERE id = 1
`

type GetConfigRow struct {
	ID                       int16              `json:"id"`
	PageID                   *string            `json:"page_id"`
	PageAccessToken          string             `json:"page_access_token"`
	PublishMode              string             `json:"publish_mode"`
	DefaultPageID            *string            `json:"default_page_id"`
	WebhookVerifyToken       *string            `json:"webhook_verify_token"`
	AppSecret                string             `json:"app_secret"`
	AiModel                  *string            `json:"ai_model"`
	AutoSchedulingEnabled    *bool              `json:"auto_scheduling_enabled"`
	AutoScheduleTimes        *string            `json:"auto_schedule_times"`
	Timezone                 *string            `json:"timezone"`
	DefaultHashtags          *string            `json:"default_hashtags"`
	EnabledContentTones      *string            `json:"enabled_content_tones"`
	CustomContentTones       *string            `json:"custom_content_tones"`
	ToneDescriptionOverrides *string            `json:"tone_description_overrides"`
	KlingEnabled             *bool              `json:"kling_enabled"`
	KlingPromptTemplate      *string            `json:"kling_prompt_template"`
	KlingResolution          *string            `json:"kling_resolution"`
	KlingAspectRatio         *string            `json:"kling_aspect_ratio"`
	KlingOutputCount         *int32             `json:"kling_output_count"`
	KlingScheduleDays        *string            `json:"kling_schedule_days"`
	KlingReferencePageUrl    *string            `json:"kling_reference_page_url"`
	KlingVideoEnabled        *bool              `json:"kling_video_enabled"`
	KlingVideoPrompts        *string            `json:"kling_video_prompts"`
	KlingVideoAspectRatio    *string            `json:"kling_video_aspect_ratio"`
	KlingVideoOutputCount    *int32             `json:"kling_video_output_count"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

// Singleton row (id = 1). Returns NULL row if missing; caller should
// fall back to a zero-value config in that case.
func (q *Queries) GetConfig(ctx context.Context) (GetConfigRow, error) {
	row := q.db.QueryRow(ctx, getConfig)
	var i GetConfigRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageAccessToken,
		&i.PublishMode,
		&i.DefaultPageID,
		&i.WebhookVerifyToken,
		&i.AppSecret,
		&i.AiModel,
		&i.AutoSchedulingEnabled,
		&i.AutoScheduleTimes,
		&i.Timezone,
		&i.DefaultHashtags,
		&i.EnabledContentTones,
		&i.CustomContentTones,
		&i.ToneDescriptionOverrides,
		&i.KlingEnabled,
		&i.KlingPromptTemplate,
		&i.KlingResolution,
		&i.KlingAspectRatio,
		&i.KlingOutputCount,
		&i.KlingScheduleDays,
		&i.KlingReferencePageUrl,
		&i.KlingVideoEnabled,
		&i.KlingVideoPrompts,
		&i.KlingVideoAspectRatio,
		&i.KlingVideoOutputCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO facebook.config (
  id, page_id, page_access_token, publish_mode, default_page_id,
  webhook_verify_token, app_secret,
  ai_model, auto_scheduling_enabled, auto_schedule_times, timezone,
  default_hashtags, enabled_content_tones, custom_content_tones,
  tone_description_overrides,
  kling_enabled, kling_prompt_template, kling_resolution,
  kling_aspect_ratio, kling_output_count, kling_schedule_days,
  kling_reference_page_url,
  kling_video_enabled, kling_video_prompts, kling_video_aspect_ratio,
  kling_video_output_count
) VALUES (
  1, $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10,
  $11, $12, $13,
  $14,
  $15, $16, $17,
  $18, $19, $20,
  $21,
  $22, $23, $24,
  $25
)
ON CONFLICT (id) DO UPDATE SET
  page_id = EXCLUDED.page_id,
  page_access_token = EXCLUDED.page_access_token,
  publish_mode = EXCLUDED.publish_mode,
  default_page_id = EXCLUDED.default_page_id,
  webhook_verify_token = EXCLUDED.webhook_verify_token,
  app_secret = EXCLUDED.app_secret,
  ai_model = EXCLUDED.ai_model,
  auto_scheduling_enabled = EXCLUDED.auto_scheduling_enabled,
  auto_schedule_times = EXCLUDED.auto_schedule_times,
  timezone = EXCLUDED.timezone,
  default_hashtags = EXCLUDED.default_hashtags,
  enabled_content_tones = EXCLUDED.enabled_content_tones,
  custom_content_tones = EXCLUDED.custom_content_tones,
  tone_description_overrides = EXCLUDED.tone_description_overrides,
  kling_enabled = EXCLUDED.kling_enabled,
  kling_prompt_template = EXCLUDED.kling_prompt_template,
  kling_resolution = EXCLUDED.kling_resolution,
  kling_aspect_ratio = EXCLUDED.kling_aspect_ratio,
  kling_output_count = EXCLUDED.kling_output_count,
  kling_schedule_days = EXCLUDED.kling_schedule_days,
  kling_reference_page_url = EXCLUDED.kling_reference_page_url,
  kling_video_enabled = EXCLUDED.kling_video_enabled,
  kling_video_prompts = EXCLUDED.kling_video_prompts,
  kling_video_aspect_ratio = EXCLUDED.kling_video_aspect_ratio,
  kling_video_output_count = EXCLUDED.kling_video_output_count,
  updated_at = now()
RETURNING
  id, page_id, page_access_token, publish_mode, default_page_id,
  webhook_verify_token, app_secret,
  ai_model, auto_scheduling_enabled, auto_schedule_times, timezone,
  default_hashtags, enabled_content_tones, custom_content_tones,
  tone_description_overrides,
  kling_enabled, kling_prompt_template, kling_resolution,
  kling_aspect_ratio, kling_output_count, kling_schedule_days,
  kling_reference_page_url,
  kling_video_enabled, kling_video_prompts, kling_video_aspect_ratio,
  kling_video_output_count,
  created_at, updated_at
`

type UpsertConfigParams struct {
	PageID                   *string `json:"page_id"`
	PageAccessToken          string  `json:"page_access_token"`
	PublishMode              string  `json:"publish_mode"`
	DefaultPageID            *string `json:"default_page_id"`
	WebhookVerifyToken       *string `json:"webhook_verify_token"`
	AppSecret                string  `json:"app_secret"`
	AiModel                  *string `json:"ai_model"`
	AutoSchedulingEnabled    *bool   `json:"auto_scheduling_enabled"`
	AutoScheduleTimes        *string `json:"auto_schedule_times"`
	Timezone                 *string `json:"timezone"`
	DefaultHashtags          *string `json:"default_hashtags"`
	EnabledContentTones      *string `json:"enabled_content_tones"`
	CustomContentTones       *string `json:"custom_content_tones"`
	ToneDescriptionOverrides *string `json:"tone_description_overrides"`
	KlingEnabled             *bool   `json:"kling_enabled"`
	KlingPromptTemplate      *string `json:"kling_prompt_template"`
	KlingResolution          *string `json:"kling_resolution"`
	KlingAspectRatio         *string `json:"kling_aspect_ratio"`
	KlingOutputCount         *int32  `json:"kling_output_count"`
	KlingScheduleDays        *string `json:"kling_schedule_days"`
	KlingReferencePageUrl    *string `json:"kling_reference_page_url"`
	KlingVideoEnabled        *bool   `json:"kling_video_enabled"`
	KlingVideoPrompts        *string `json:"kling_video_prompts"`
	KlingVideoAspectRatio    *string `json:"kling_video_aspect_ratio"`
	KlingVideoOutputCount    *int32  `json:"kling_video_output_count"`
}

type UpsertConfigRow struct {
	ID                       int16              `json:"id"`
	PageID                   *string            `json:"page_id"`
	PageAccessToken          string             `json:"page_access_token"`
	PublishMode              string             `json:"publish_mode"`
	DefaultPageID            *string            `json:"default_page_id"`
	WebhookVerifyToken       *string            `json:"webhook_verify_token"`
	AppSecret                string             `json:"app_secret"`
	AiModel                  *string            `json:"ai_model"`
	AutoSchedulingEnabled    *bool              `json:"auto_scheduling_enabled"`
	AutoScheduleTimes        *string            `json:"auto_schedule_times"`
	Timezone                 *string            `json:"timezone"`
	DefaultHashtags          *string            `json:"default_hashtags"`
	EnabledContentTones      *string            `json:"enabled_content_tones"`
	CustomContentTones       *string            `json:"custom_content_tones"`
	ToneDescriptionOverrides *string            `json:"tone_description_overrides"`
	KlingEnabled             *bool              `json:"kling_enabled"`
	KlingPromptTemplate      *string            `json:"kling_prompt_template"`
	KlingResolution          *string            `json:"kling_resolution"`
	KlingAspectRatio         *string            `json:"kling_aspect_ratio"`
	KlingOutputCount         *int32             `json:"kling_output_count"`
	KlingScheduleDays        *string            `json:"kling_schedule_days"`
	KlingReferencePageUrl    *string            `json:"kling_reference_page_url"`
	KlingVideoEnabled        *bool              `json:"kling_video_enabled"`
	KlingVideoPrompts        *string            `json:"kling_video_prompts"`
	KlingVideoAspectRatio    *string            `json:"kling_video_aspect_ratio"`
	KlingVideoOutputCount    *int32             `json:"kling_video_output_count"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (UpsertConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertConfig,
		arg.PageID,
		arg.PageAccessToken,
		arg.PublishMode,
		arg.DefaultPageID,
		arg.WebhookVerifyToken,
		arg.AppSecret,
		arg.AiModel,
		arg.AutoSchedulingEnabled,
		arg.AutoScheduleTimes,
		arg.Timezone,
		arg.DefaultHashtags,
		arg.EnabledContentTones,
		arg.CustomContentTones,
		arg.ToneDescriptionOverrides,
		arg.KlingEnabled,
		arg.KlingPromptTemplate,
		arg.KlingResolution,
		arg.KlingAspectRatio,
		arg.KlingOutputCount,
		arg.KlingScheduleDays,
		arg.KlingReferencePageUrl,
		arg.KlingVideoEnabled,
		arg.KlingVideoPrompts,
		arg.KlingVideoAspectRatio,
		arg.KlingVideoOutputCount,
	)
	var i UpsertConfigRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageAccessToken,
		&i.PublishMode,
		&i.DefaultPageID,
		&i.WebhookVerifyToken,
		&i.AppSecret,
		&i.AiModel,
		&i.AutoSchedulingEnabled,
		&i.AutoScheduleTimes,
		&i.Timezone,
		&i.DefaultHashtags,
		&i.EnabledContentTones,
		&i.CustomContentTones,
		&i.ToneDescriptionOverrides,
		&i.KlingEnabled,
		&i.KlingPromptTemplate,
		&i.KlingResolution,
		&i.KlingAspectRatio,
		&i.KlingOutputCount,
		&i.KlingScheduleDays,
		&i.KlingReferencePageUrl,
		&i.KlingVideoEnabled,
		&i.KlingVideoPrompts,
		&i.KlingVideoAspectRatio,
		&i.KlingVideoOutputCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
