// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO facebook.conversations (
  page_id, customer_id, customer_name, last_message_preview, last_message_time,
  status, ai_enabled, priority_score, collected_info, reset_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING
  id, page_id, customer_id, customer_name, last_message_preview, last_message_time,
  unread_count, status, ai_enabled, contacted, priority_score, conversation_summary,
  collected_info, reset_at, created_at, updated_at
`

type CreateConversationParams struct {
	PageID             pgtype.UUID        `json:"page_id"`
	CustomerID         string             `json:"customer_id"`
	CustomerName       string             `json:"customer_name"`
	LastMessagePreview *string            `json:"last_message_preview"`
	LastMessageTime    pgtype.Timestamptz `json:"last_message_time"`
	Status             string             `json:"status"`
	AiEnabled          bool               `json:"ai_enabled"`
	PriorityScore      int32              `json:"priority_score"`
	CollectedInfo      json.RawMessage    `json:"collected_info"`
	ResetAt            pgtype.Timestamptz `json:"reset_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (FacebookConversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.PageID,
		arg.CustomerID,
		arg.CustomerName,
		arg.LastMessagePreview,
		arg.LastMessageTime,
		arg.Status,
		arg.AiEnabled,
		arg.PriorityScore,
		arg.CollectedInfo,
		arg.ResetAt,
	)
	var i FacebookConversation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.CustomerID,
		&i.CustomerName,
		&i.LastMessagePreview,
		&i.LastMessageTime,
		&i.UnreadCount,
		&i.Status,
		&i.AiEnabled,
		&i.Contacted,
		&i.PriorityScore,
		&i.ConversationSummary,
		&i.CollectedInfo,
		&i.ResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT
  id, page_id, customer_id, customer_name, last_message_preview, last_message_time,
  unread_count, status, ai_enabled, contacted, priority_score, conversation_summary,
  collected_info, reset_at, created_at, updated_at
FROM facebook.conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (FacebookConversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i FacebookConversation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.CustomerID,
		&i.CustomerName,
		&i.LastMessagePreview,
		&i.LastMessageTime,
		&i.UnreadCount,
		&i.Status,
		&i.AiEnabled,
		&i.Contacted,
		&i.PriorityScore,
		&i.ConversationSummary,
		&i.CollectedInfo,
		&i.ResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByCustomer = `-- name: GetConversationByCustomer :one
SELECT
  id, page_id, customer_id, customer_name, last_message_preview, last_message_time,
  unread_count, status, ai_enabled, contacted, priority_score, conversation_summary,
  collected_info, reset_at, created_at, updated_at
FROM facebook.conversations
WHERE page_id = $1 AND customer_id = $2
`

type GetConversationByCustomerParams struct {
	PageID     pgtype.UUID `json:"page_id"`
	CustomerID string      `json:"customer_id"`
}

func (q *Queries) GetConversationByCustomer(ctx context.Context, arg GetConversationByCustomerParams) (FacebookConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByCustomer, arg.PageID, arg.CustomerID)
	var i FacebookConversation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.CustomerID,
		&i.CustomerName,
		&i.LastMessagePreview,
		&i.LastMessageTime,
		&i.UnreadCount,
		&i.Status,
		&i.AiEnabled,
		&i.Contacted,
		&i.PriorityScore,
		&i.ConversationSummary,
		&i.CollectedInfo,
		&i.ResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT
  id, page_id, customer_id, customer_name, last_message_preview, last_message_time,
  unread_count, status, ai_enabled, contacted, priority_score, conversation_summary,
  collected_info, reset_at, created_at, updated_at
FROM facebook.conversations
WHERE page_id = $1 AND status = 'open'
ORDER BY updated_at DESC
LIMIT $2
`

type ListConversationsParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]FacebookConversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.PageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookConversation{}
	for rows.Next() {
		var i FacebookConversation
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.CustomerID,
			&i.CustomerName,
			&i.LastMessagePreview,
			&i.LastMessageTime,
			&i.UnreadCount,
			&i.Status,
			&i.AiEnabled,
			&i.Contacted,
			&i.PriorityScore,
			&i.ConversationSummary,
			&i.CollectedInfo,
			&i.ResetAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationContacted = `-- name: MarkConversationContacted :exec
UPDATE facebook.conversations
SET contacted = $2,
    updated_at = now()
WHERE id = $1
`

type MarkConversationContactedParams struct {
	ID        pgtype.UUID `json:"id"`
	Contacted bool        `json:"contacted"`
}

func (q *Queries) MarkConversationContacted(ctx context.Context, arg MarkConversationContactedParams) error {
	_, err := q.db.Exec(ctx, markConversationContacted, arg.ID, arg.Contacted)
	return err
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE facebook.conversations
SET unread_count = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkConversationRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markConversationRead, id)
	return err
}

const resetConversationTurns = `-- name: ResetConversationTurns :exec
UPDATE facebook.conversations
SET reset_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetConversationTurns(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetConversationTurns, id)
	return err
}

const scanConversationsNeedingReply = `-- name: ScanConversationsNeedingReply :many
SELECT
  id, page_id, customer_id, customer_name, last_message_preview, last_message_time,
  unread_count, status, ai_enabled, contacted, priority_score, conversation_summary,
  collected_info, reset_at, created_at, updated_at
FROM facebook.conversations
WHERE page_id = $1
  AND status = 'open'
  AND ai_enabled = true
  AND (
    unread_count > 0
    OR updated_at > now() - interval '24 hours'
  )
ORDER BY updated_at DESC
LIMIT $2
`

type ScanConversationsNeedingReplyParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Limit  int32       `json:"limit"`
}

// Finds open conversations updated in the last 24h that have unread messages
// or were last updated without an AI reply.
func (q *Queries) ScanConversationsNeedingReply(ctx context.Context, arg ScanConversationsNeedingReplyParams) ([]FacebookConversation, error) {
	rows, err := q.db.Query(ctx, scanConversationsNeedingReply, arg.PageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookConversation{}
	for rows.Next() {
		var i FacebookConversation
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.CustomerID,
			&i.CustomerName,
			&i.LastMessagePreview,
			&i.LastMessageTime,
			&i.UnreadCount,
			&i.Status,
			&i.AiEnabled,
			&i.Contacted,
			&i.PriorityScore,
			&i.ConversationSummary,
			&i.CollectedInfo,
			&i.ResetAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleConversationAI = `-- name: ToggleConversationAI :exec
UPDATE facebook.conversations
SET ai_enabled = $2,
    updated_at = now()
WHERE id = $1
`

type ToggleConversationAIParams struct {
	ID        pgtype.UUID `json:"id"`
	AiEnabled bool        `json:"ai_enabled"`
}

func (q *Queries) ToggleConversationAI(ctx context.Context, arg ToggleConversationAIParams) error {
	_, err := q.db.Exec(ctx, toggleConversationAI, arg.ID, arg.AiEnabled)
	return err
}

const updateConversationPreview = `-- name: UpdateConversationPreview :exec
UPDATE facebook.conversations
SET last_message_preview = $2,
    last_message_time = $3,
    unread_count = unread_count + $4,
    updated_at = now()
WHERE id = $1
`

type UpdateConversationPreviewParams struct {
	ID                 pgtype.UUID        `json:"id"`
	LastMessagePreview *string            `json:"last_message_preview"`
	LastMessageTime    pgtype.Timestamptz `json:"last_message_time"`
	UnreadCount        int32              `json:"unread_count"`
}

func (q *Queries) UpdateConversationPreview(ctx context.Context, arg UpdateConversationPreviewParams) error {
	_, err := q.db.Exec(ctx, updateConversationPreview,
		arg.ID,
		arg.LastMessagePreview,
		arg.LastMessageTime,
		arg.UnreadCount,
	)
	return err
}

const updateConversationSummary = `-- name: UpdateConversationSummary :exec
UPDATE facebook.conversations
SET conversation_summary = $2,
    collected_info = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateConversationSummaryParams struct {
	ID                  pgtype.UUID     `json:"id"`
	ConversationSummary *string         `json:"conversation_summary"`
	CollectedInfo       json.RawMessage `json:"collected_info"`
}

func (q *Queries) UpdateConversationSummary(ctx context.Context, arg UpdateConversationSummaryParams) error {
	_, err := q.db.Exec(ctx, updateConversationSummary, arg.ID, arg.ConversationSummary, arg.CollectedInfo)
	return err
}
