// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extras.sql

package db

import (
	"context"
)

const addHashtag = `-- name: AddHashtag :one
INSERT INTO facebook.hashtag_bank (tag, category)
VALUES ($1, $2)
ON CONFLICT (tag) DO UPDATE SET category = EXCLUDED.category
RETURNING tag, category, created_at
`

type AddHashtagParams struct {
	Tag      string  `json:"tag"`
	Category *string `json:"category"`
}

func (q *Queries) AddHashtag(ctx context.Context, arg AddHashtagParams) (FacebookHashtagBank, error) {
	row := q.db.QueryRow(ctx, addHashtag, arg.Tag, arg.Category)
	var i FacebookHashtagBank
	err := row.Scan(&i.Tag, &i.Category, &i.CreatedAt)
	return i, err
}

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO facebook.prompt_templates (
  id, name, category, prompt_text, variables_json, description, is_active, supported_tones
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, category, prompt_text, variables_json, description, is_active, supported_tones, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Category       string  `json:"category"`
	PromptText     string  `json:"prompt_text"`
	VariablesJson  string  `json:"variables_json"`
	Description    *string `json:"description"`
	IsActive       bool    `json:"is_active"`
	SupportedTones string  `json:"supported_tones"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (FacebookPromptTemplate, error) {
	row := q.db.QueryRow(ctx, createPromptTemplate,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.PromptText,
		arg.VariablesJson,
		arg.Description,
		arg.IsActive,
		arg.SupportedTones,
	)
	var i FacebookPromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PromptText,
		&i.VariablesJson,
		&i.Description,
		&i.IsActive,
		&i.SupportedTones,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHashtag = `-- name: DeleteHashtag :exec
DELETE FROM facebook.hashtag_bank WHERE tag = $1
`

func (q *Queries) DeleteHashtag(ctx context.Context, tag string) error {
	_, err := q.db.Exec(ctx, deleteHashtag, tag)
	return err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :exec
DELETE FROM facebook.prompt_templates WHERE id = $1
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePromptTemplate, id)
	return err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, name, category, prompt_text, variables_json, description, is_active, supported_tones, created_at, updated_at
FROM facebook.prompt_templates
WHERE id = $1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id string) (FacebookPromptTemplate, error) {
	row := q.db.QueryRow(ctx, getPromptTemplate, id)
	var i FacebookPromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PromptText,
		&i.VariablesJson,
		&i.Description,
		&i.IsActive,
		&i.SupportedTones,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoConfig = `-- name: GetVideoConfig :one
SELECT id, watermark_type, watermark_text, watermark_image_path, updated_at
FROM facebook.video_config
WHERE id = 1
`

// Video Config (singleton)
func (q *Queries) GetVideoConfig(ctx context.Context) (FacebookVideoConfig, error) {
	row := q.db.QueryRow(ctx, getVideoConfig)
	var i FacebookVideoConfig
	err := row.Scan(
		&i.ID,
		&i.WatermarkType,
		&i.WatermarkText,
		&i.WatermarkImagePath,
		&i.UpdatedAt,
	)
	return i, err
}

const listHashtags = `-- name: ListHashtags :many
SELECT tag, category, created_at
FROM facebook.hashtag_bank
ORDER BY created_at DESC
`

// Hashtag Bank
func (q *Queries) ListHashtags(ctx context.Context) ([]FacebookHashtagBank, error) {
	rows, err := q.db.Query(ctx, listHashtags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookHashtagBank{}
	for rows.Next() {
		var i FacebookHashtagBank
		if err := rows.Scan(&i.Tag, &i.Category, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, name, category, prompt_text, variables_json, description, is_active, supported_tones, created_at, updated_at
FROM facebook.prompt_templates
WHERE category = $1 OR $1 = ''
ORDER BY updated_at DESC
`

// Prompt Templates
func (q *Queries) ListPromptTemplates(ctx context.Context, category string) ([]FacebookPromptTemplate, error) {
	rows, err := q.db.Query(ctx, listPromptTemplates, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookPromptTemplate{}
	for rows.Next() {
		var i FacebookPromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.PromptText,
			&i.VariablesJson,
			&i.Description,
			&i.IsActive,
			&i.SupportedTones,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptTemplate = `-- name: UpdatePromptTemplate :one
UPDATE facebook.prompt_templates
SET name = $2,
    category = $3,
    prompt_text = $4,
    variables_json = $5,
    description = $6,
    is_active = $7,
    supported_tones = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, category, prompt_text, variables_json, description, is_active, supported_tones, created_at, updated_at
`

type UpdatePromptTemplateParams struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Category       string  `json:"category"`
	PromptText     string  `json:"prompt_text"`
	VariablesJson  string  `json:"variables_json"`
	Description    *string `json:"description"`
	IsActive       bool    `json:"is_active"`
	SupportedTones string  `json:"supported_tones"`
}

func (q *Queries) UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (FacebookPromptTemplate, error) {
	row := q.db.QueryRow(ctx, updatePromptTemplate,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.PromptText,
		arg.VariablesJson,
		arg.Description,
		arg.IsActive,
		arg.SupportedTones,
	)
	var i FacebookPromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.PromptText,
		&i.VariablesJson,
		&i.Description,
		&i.IsActive,
		&i.SupportedTones,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVideoConfig = `-- name: UpsertVideoConfig :one
INSERT INTO facebook.video_config (
  id, watermark_type, watermark_text, watermark_image_path
) VALUES (1, $1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
  watermark_type = EXCLUDED.watermark_type,
  watermark_text = EXCLUDED.watermark_text,
  watermark_image_path = EXCLUDED.watermark_image_path,
  updated_at = now()
RETURNING id, watermark_type, watermark_text, watermark_image_path, updated_at
`

type UpsertVideoConfigParams struct {
	WatermarkType      string  `json:"watermark_type"`
	WatermarkText      *string `json:"watermark_text"`
	WatermarkImagePath *string `json:"watermark_image_path"`
}

func (q *Queries) UpsertVideoConfig(ctx context.Context, arg UpsertVideoConfigParams) (FacebookVideoConfig, error) {
	row := q.db.QueryRow(ctx, upsertVideoConfig, arg.WatermarkType, arg.WatermarkText, arg.WatermarkImagePath)
	var i FacebookVideoConfig
	err := row.Scan(
		&i.ID,
		&i.WatermarkType,
		&i.WatermarkText,
		&i.WatermarkImagePath,
		&i.UpdatedAt,
	)
	return i, err
}
