// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAITurns = `-- name: CountAITurns :one
SELECT COUNT(*) AS ai_turn_count
FROM facebook.messages
WHERE conversation_id = $1 AND is_ai_generated = true
`

func (q *Queries) CountAITurns(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAITurns, conversationID)
	var ai_turn_count int64
	err := row.Scan(&ai_turn_count)
	return ai_turn_count, err
}

const getMessage = `-- name: GetMessage :one
SELECT
  id, conversation_id, sender_id, sender_type, content, message_type,
  is_from_page, is_ai_generated, is_read, sent_at, created_at
FROM facebook.messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (FacebookMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i FacebookMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.SenderType,
		&i.Content,
		&i.MessageType,
		&i.IsFromPage,
		&i.IsAiGenerated,
		&i.IsRead,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasAIReplied = `-- name: HasAIReplied :one
SELECT EXISTS(
  SELECT 1 FROM facebook.ai_replied WHERE inbound_message_id = $1
) AS has_replied
`

func (q *Queries) HasAIReplied(ctx context.Context, inboundMessageID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasAIReplied, inboundMessageID)
	var has_replied bool
	err := row.Scan(&has_replied)
	return has_replied, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO facebook.messages (
  id, conversation_id, sender_id, sender_type, content, message_type,
  is_from_page, is_ai_generated, is_read, sent_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO NOTHING
`

type InsertMessageParams struct {
	ID             string             `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       string             `json:"sender_id"`
	SenderType     string             `json:"sender_type"`
	Content        string             `json:"content"`
	MessageType    string             `json:"message_type"`
	IsFromPage     bool               `json:"is_from_page"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	IsRead         bool               `json:"is_read"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.SenderType,
		arg.Content,
		arg.MessageType,
		arg.IsFromPage,
		arg.IsAiGenerated,
		arg.IsRead,
		arg.SentAt,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
SELECT
  id, conversation_id, sender_id, sender_type, content, message_type,
  is_from_page, is_ai_generated, is_read, sent_at, created_at
FROM facebook.messages
WHERE conversation_id = $1
ORDER BY sent_at DESC
LIMIT $2
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]FacebookMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookMessage{}
	for rows.Next() {
		var i FacebookMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderType,
			&i.Content,
			&i.MessageType,
			&i.IsFromPage,
			&i.IsAiGenerated,
			&i.IsRead,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
