// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type FacebookAccountLoginSession struct {
	ID          pgtype.UUID        `json:"id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	LastError   *string            `json:"last_error"`
	ProfilePath *string            `json:"profile_path"`
	CookiesJson []byte             `json:"cookies_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FacebookAiPersona struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	SystemPrompt      string             `json:"system_prompt"`
	FewShotExamples   *string            `json:"few_shot_examples"`
	PostProcessorType string             `json:"post_processor_type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FacebookAiReplied struct {
	InboundMessageID  string             `json:"inbound_message_id"`
	OutboundMessageID *string            `json:"outbound_message_id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	RepliedAt         pgtype.Timestamptz `json:"replied_at"`
}

type FacebookBrainDraft struct {
	ID                pgtype.UUID        `json:"id"`
	FeedID            pgtype.UUID        `json:"feed_id"`
	Content           string             `json:"content"`
	ProvenanceID      string             `json:"provenance_id"`
	ValidationStatus  string             `json:"validation_status"`
	ValidationDetails []byte             `json:"validation_details"`
	Warnings          []byte             `json:"warnings"`
	KanbanJobID       *string            `json:"kanban_job_id"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FacebookBrainFeed struct {
	ID             pgtype.UUID        `json:"id"`
	CrawledPostID  string             `json:"crawled_post_id"`
	PageID         string             `json:"page_id"`
	PageName       *string            `json:"page_name"`
	Content        string             `json:"content"`
	MediaUrls      []byte             `json:"media_urls"`
	VideoUrls      []byte             `json:"video_urls"`
	ThumbnailUrls  []byte             `json:"thumbnail_urls"`
	FullPicture    *string            `json:"full_picture"`
	MediaType      string             `json:"media_type"`
	Likes          int32              `json:"likes"`
	Comments       int32              `json:"comments"`
	Shares         int32              `json:"shares"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
	SourceUrl      string             `json:"source_url"`
	Permalink      string             `json:"permalink"`
	BrainContentID *string            `json:"brain_content_id"`
	IngestedAt     pgtype.Timestamptz `json:"ingested_at"`
	ErrorMessage   *string            `json:"error_message"`
	Status         string             `json:"status"`
	RetryCount     int32              `json:"retry_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FacebookComment struct {
	ID                 string             `json:"id"`
	PostID             string             `json:"post_id"`
	PageID             pgtype.UUID        `json:"page_id"`
	FromID             *string            `json:"from_id"`
	FromName           string             `json:"from_name"`
	Message            string             `json:"message"`
	CreatedTime        pgtype.Timestamptz `json:"created_time"`
	LikeCount          int32              `json:"like_count"`
	ReplyCount         int32              `json:"reply_count"`
	Sentiment          string             `json:"sentiment"`
	Intent             string             `json:"intent"`
	Priority           int32              `json:"priority"`
	IsHidden           bool               `json:"is_hidden"`
	IsLiked            bool               `json:"is_liked"`
	IsPrivateReplySent bool               `json:"is_private_reply_sent"`
	CollectedInfo      json.RawMessage    `json:"collected_info"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedAt          pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy          *string            `json:"claimed_by"`
	Processed          bool               `json:"processed"`
}

type FacebookCommentReply struct {
	ID              pgtype.UUID        `json:"id"`
	CommentID       string             `json:"comment_id"`
	ReplyType       string             `json:"reply_type"`
	Content         string             `json:"content"`
	SentBy          string             `json:"sent_by"`
	Status          string             `json:"status"`
	FacebookReplyID *string            `json:"facebook_reply_id"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
}

type FacebookConfig struct {
	ID                       int16              `json:"id"`
	PageID                   *string            `json:"page_id"`
	PageAccessToken          string             `json:"page_access_token"`
	PublishMode              string             `json:"publish_mode"`
	DefaultPageID            *string            `json:"default_page_id"`
	WebhookVerifyToken       *string            `json:"webhook_verify_token"`
	AppSecret                string             `json:"app_secret"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	AiModel                  *string            `json:"ai_model"`
	AutoSchedulingEnabled    *bool              `json:"auto_scheduling_enabled"`
	AutoScheduleTimes        *string            `json:"auto_schedule_times"`
	Timezone                 *string            `json:"timezone"`
	DefaultHashtags          *string            `json:"default_hashtags"`
	EnabledContentTones      *string            `json:"enabled_content_tones"`
	CustomContentTones       *string            `json:"custom_content_tones"`
	ToneDescriptionOverrides *string            `json:"tone_description_overrides"`
	KlingEnabled             *bool              `json:"kling_enabled"`
	KlingPromptTemplate      *string            `json:"kling_prompt_template"`
	KlingResolution          *string            `json:"kling_resolution"`
	KlingAspectRatio         *string            `json:"kling_aspect_ratio"`
	KlingOutputCount         *int32             `json:"kling_output_count"`
	KlingScheduleDays        *string            `json:"kling_schedule_days"`
	KlingReferencePageUrl    *string            `json:"kling_reference_page_url"`
	KlingVideoEnabled        *bool              `json:"kling_video_enabled"`
	KlingVideoPrompts        *string            `json:"kling_video_prompts"`
	KlingVideoAspectRatio    *string            `json:"kling_video_aspect_ratio"`
	KlingVideoOutputCount    *int32             `json:"kling_video_output_count"`
}

type FacebookContentQueue struct {
	ID               pgtype.UUID        `json:"id"`
	PageID           pgtype.UUID        `json:"page_id"`
	Content          string             `json:"content"`
	ImageUrl         *string            `json:"image_url"`
	MediaUrls        []byte             `json:"media_urls"`
	Source           string             `json:"source"`
	Status           string             `json:"status"`
	TrendID          *string            `json:"trend_id"`
	PromptTemplateID *string            `json:"prompt_template_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type FacebookConversation struct {
	ID                  pgtype.UUID        `json:"id"`
	PageID              pgtype.UUID        `json:"page_id"`
	CustomerID          string             `json:"customer_id"`
	CustomerName        string             `json:"customer_name"`
	LastMessagePreview  *string            `json:"last_message_preview"`
	LastMessageTime     pgtype.Timestamptz `json:"last_message_time"`
	UnreadCount         int32              `json:"unread_count"`
	Status              string             `json:"status"`
	AiEnabled           bool               `json:"ai_enabled"`
	Contacted           bool               `json:"contacted"`
	PriorityScore       int32              `json:"priority_score"`
	ConversationSummary *string            `json:"conversation_summary"`
	CollectedInfo       json.RawMessage    `json:"collected_info"`
	ResetAt             pgtype.Timestamptz `json:"reset_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FacebookCrawledPost struct {
	ID            pgtype.UUID        `json:"id"`
	PageID        string             `json:"page_id"`
	SourceUrl     string             `json:"source_url"`
	FbPostID      *string            `json:"fb_post_id"`
	Content       *string            `json:"content"`
	MediaUrls     []byte             `json:"media_urls"`
	MediaType     string             `json:"media_type"`
	Likes         int32              `json:"likes"`
	Comments      int32              `json:"comments"`
	Shares        int32              `json:"shares"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	Permalink     *string            `json:"permalink"`
	IsSelected    bool               `json:"is_selected"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	VideoUrls     []byte             `json:"video_urls"`
	ThumbnailUrls []byte             `json:"thumbnail_urls"`
	FullPicture   string             `json:"full_picture"`
	ReactionIcons []byte             `json:"reaction_icons"`
}

type FacebookFbGroup struct {
	ID                pgtype.UUID        `json:"id"`
	GroupID           string             `json:"group_id"`
	Name              *string            `json:"name"`
	AssignedAccountID pgtype.UUID        `json:"assigned_account_id"`
	Status            string             `json:"status"`
	LastPostedAt      pgtype.Timestamptz `json:"last_posted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type FacebookHashtagBank struct {
	Tag       string             `json:"tag"`
	Category  *string            `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FacebookMessage struct {
	ID             string             `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       string             `json:"sender_id"`
	SenderType     string             `json:"sender_type"`
	Content        string             `json:"content"`
	MessageType    string             `json:"message_type"`
	IsFromPage     bool               `json:"is_from_page"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	IsRead         bool               `json:"is_read"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FacebookPage struct {
	ID               pgtype.UUID        `json:"id"`
	PageID           string             `json:"page_id"`
	PageName         string             `json:"page_name"`
	PageAccessToken  string             `json:"page_access_token"`
	Category         *string            `json:"category"`
	IsActive         bool               `json:"is_active"`
	PostingEnabled   bool               `json:"posting_enabled"`
	AiEnabled        bool               `json:"ai_enabled"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	AvatarUrl        *string            `json:"avatar_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AiRole           *string            `json:"ai_role"`
	AiIndustry       *string            `json:"ai_industry"`
	AiTone           *string            `json:"ai_tone"`
	AiPriceList      *string            `json:"ai_price_list"`
	AiLocationInfo   *string            `json:"ai_location_info"`
	AiContactChannel *string            `json:"ai_contact_channel"`
	AiExtraRules     *string            `json:"ai_extra_rules"`
	AiSystemPrompt   *string            `json:"ai_system_prompt"`
	AiPersonaID      pgtype.UUID        `json:"ai_persona_id"`
}

type FacebookPostHistory struct {
	ID             pgtype.UUID        `json:"id"`
	PostID         string             `json:"post_id"`
	PageID         pgtype.UUID        `json:"page_id"`
	Content        string             `json:"content"`
	ImageUrl       *string            `json:"image_url"`
	MediaUrls      []byte             `json:"media_urls"`
	PostUrl        *string            `json:"post_url"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Likes          int32              `json:"likes"`
	Comments       int32              `json:"comments"`
	Shares         int32              `json:"shares"`
	Reach          *int32             `json:"reach"`
	EngagementRate pgtype.Numeric     `json:"engagement_rate"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FacebookPromptTemplate struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Category       string             `json:"category"`
	PromptText     string             `json:"prompt_text"`
	VariablesJson  string             `json:"variables_json"`
	Description    *string            `json:"description"`
	IsActive       bool               `json:"is_active"`
	SupportedTones string             `json:"supported_tones"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FacebookRepostCampaign struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	SourcePostUrl       string             `json:"source_post_url"`
	SourcePostText      string             `json:"source_post_text"`
	SourcePostMediaUrls []byte             `json:"source_post_media_urls"`
	CaptionStyle        string             `json:"caption_style"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	LastError           *string            `json:"last_error"`
}

type FacebookRepostJob struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	GroupID          string             `json:"group_id"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	LastError        *string            `json:"last_error"`
	PostUrl          *string            `json:"post_url"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	AnonymousPosting bool               `json:"anonymous_posting"`
	AutoEnabled      bool               `json:"auto_enabled"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type FacebookScheduledPost struct {
	ID                   pgtype.UUID        `json:"id"`
	PageID               pgtype.UUID        `json:"page_id"`
	Content              string             `json:"content"`
	ImageUrl             *string            `json:"image_url"`
	MediaUrls            []byte             `json:"media_urls"`
	Status               string             `json:"status"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	PostType             string             `json:"post_type"`
	TrendReference       *string            `json:"trend_reference"`
	AiGenerated          bool               `json:"ai_generated"`
	EngagementPrediction []byte             `json:"engagement_prediction"`
	CampaignID           *string            `json:"campaign_id"`
	FacebookPostID       *string            `json:"facebook_post_id"`
	ErrorMessage         *string            `json:"error_message"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type FacebookVideoConfig struct {
	ID                 int16              `json:"id"`
	WatermarkType      string             `json:"watermark_type"`
	WatermarkText      *string            `json:"watermark_text"`
	WatermarkImagePath *string            `json:"watermark_image_path"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FacebookWebhookEvent struct {
	ID              pgtype.UUID        `json:"id"`
	EventType       string             `json:"event_type"`
	FacebookEntryID *string            `json:"facebook_entry_id"`
	Payload         json.RawMessage    `json:"payload"`
	Signature       *string            `json:"signature"`
	Processed       bool               `json:"processed"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage    *string            `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
