// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO facebook.pages (
  page_id, page_name, page_access_token, category, is_active,
  posting_enabled, ai_enabled, avatar_url,
  ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
  ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type CreatePageParams struct {
	PageID           string      `json:"page_id"`
	PageName         string      `json:"page_name"`
	PageAccessToken  string      `json:"page_access_token"`
	Category         *string     `json:"category"`
	IsActive         bool        `json:"is_active"`
	PostingEnabled   bool        `json:"posting_enabled"`
	AiEnabled        bool        `json:"ai_enabled"`
	AvatarUrl        *string     `json:"avatar_url"`
	AiRole           *string     `json:"ai_role"`
	AiIndustry       *string     `json:"ai_industry"`
	AiTone           *string     `json:"ai_tone"`
	AiPriceList      *string     `json:"ai_price_list"`
	AiLocationInfo   *string     `json:"ai_location_info"`
	AiContactChannel *string     `json:"ai_contact_channel"`
	AiExtraRules     *string     `json:"ai_extra_rules"`
	AiSystemPrompt   *string     `json:"ai_system_prompt"`
	AiPersonaID      pgtype.UUID `json:"ai_persona_id"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.PageID,
		arg.PageName,
		arg.PageAccessToken,
		arg.Category,
		arg.IsActive,
		arg.PostingEnabled,
		arg.AiEnabled,
		arg.AvatarUrl,
		arg.AiRole,
		arg.AiIndustry,
		arg.AiTone,
		arg.AiPriceList,
		arg.AiLocationInfo,
		arg.AiContactChannel,
		arg.AiExtraRules,
		arg.AiSystemPrompt,
		arg.AiPersonaID,
	)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM facebook.pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT
  id, page_id, page_name, page_access_token, category, is_active,
  posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
  ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
  ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
FROM facebook.pages
WHERE id = $1
`

func (q *Queries) GetPage(ctx context.Context, id pgtype.UUID) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const getPageByFBID = `-- name: GetPageByFBID :one
SELECT
  id, page_id, page_name, page_access_token, category, is_active,
  posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
  ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
  ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
FROM facebook.pages
WHERE page_id = $1
`

func (q *Queries) GetPageByFBID(ctx context.Context, pageID string) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, getPageByFBID, pageID)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT
  id, page_id, page_name, page_access_token, category, is_active,
  posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
  ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
  ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
FROM facebook.pages
ORDER BY page_name ASC
`

// Returns all managed pages ordered by name.
func (q *Queries) ListPages(ctx context.Context) ([]FacebookPage, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookPage{}
	for rows.Next() {
		var i FacebookPage
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.PageName,
			&i.PageAccessToken,
			&i.Category,
			&i.IsActive,
			&i.PostingEnabled,
			&i.AiEnabled,
			&i.LastActiveAt,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AiRole,
			&i.AiIndustry,
			&i.AiTone,
			&i.AiPriceList,
			&i.AiLocationInfo,
			&i.AiContactChannel,
			&i.AiExtraRules,
			&i.AiSystemPrompt,
			&i.AiPersonaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePageAI = `-- name: TogglePageAI :one
UPDATE facebook.pages
SET ai_enabled = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type TogglePageAIParams struct {
	ID        pgtype.UUID `json:"id"`
	AiEnabled bool        `json:"ai_enabled"`
}

func (q *Queries) TogglePageAI(ctx context.Context, arg TogglePageAIParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, togglePageAI, arg.ID, arg.AiEnabled)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const togglePagePosting = `-- name: TogglePagePosting :one
UPDATE facebook.pages
SET posting_enabled = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type TogglePagePostingParams struct {
	ID             pgtype.UUID `json:"id"`
	PostingEnabled bool        `json:"posting_enabled"`
}

func (q *Queries) TogglePagePosting(ctx context.Context, arg TogglePagePostingParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, togglePagePosting, arg.ID, arg.PostingEnabled)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE facebook.pages
SET page_name = $2,
    page_access_token = $3,
    category = $4,
    is_active = $5,
    posting_enabled = $6,
    ai_enabled = $7,
    avatar_url = $8,
    ai_role = $9,
    ai_industry = $10,
    ai_tone = $11,
    ai_price_list = $12,
    ai_location_info = $13,
    ai_contact_channel = $14,
    ai_extra_rules = $15,
    ai_system_prompt = $16,
    ai_persona_id = $17,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type UpdatePageParams struct {
	ID               pgtype.UUID `json:"id"`
	PageName         string      `json:"page_name"`
	PageAccessToken  string      `json:"page_access_token"`
	Category         *string     `json:"category"`
	IsActive         bool        `json:"is_active"`
	PostingEnabled   bool        `json:"posting_enabled"`
	AiEnabled        bool        `json:"ai_enabled"`
	AvatarUrl        *string     `json:"avatar_url"`
	AiRole           *string     `json:"ai_role"`
	AiIndustry       *string     `json:"ai_industry"`
	AiTone           *string     `json:"ai_tone"`
	AiPriceList      *string     `json:"ai_price_list"`
	AiLocationInfo   *string     `json:"ai_location_info"`
	AiContactChannel *string     `json:"ai_contact_channel"`
	AiExtraRules     *string     `json:"ai_extra_rules"`
	AiSystemPrompt   *string     `json:"ai_system_prompt"`
	AiPersonaID      pgtype.UUID `json:"ai_persona_id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ID,
		arg.PageName,
		arg.PageAccessToken,
		arg.Category,
		arg.IsActive,
		arg.PostingEnabled,
		arg.AiEnabled,
		arg.AvatarUrl,
		arg.AiRole,
		arg.AiIndustry,
		arg.AiTone,
		arg.AiPriceList,
		arg.AiLocationInfo,
		arg.AiContactChannel,
		arg.AiExtraRules,
		arg.AiSystemPrompt,
		arg.AiPersonaID,
	)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}

const updatePagePersona = `-- name: UpdatePagePersona :one
UPDATE facebook.pages
SET ai_role = $2,
    ai_industry = $3,
    ai_tone = $4,
    ai_price_list = $5,
    ai_location_info = $6,
    ai_contact_channel = $7,
    ai_extra_rules = $8,
    ai_system_prompt = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, page_name, page_access_token, category, is_active,
          posting_enabled, ai_enabled, last_active_at, avatar_url, created_at, updated_at,
          ai_role, ai_industry, ai_tone, ai_price_list, ai_location_info,
          ai_contact_channel, ai_extra_rules, ai_system_prompt, ai_persona_id
`

type UpdatePagePersonaParams struct {
	ID               pgtype.UUID `json:"id"`
	AiRole           *string     `json:"ai_role"`
	AiIndustry       *string     `json:"ai_industry"`
	AiTone           *string     `json:"ai_tone"`
	AiPriceList      *string     `json:"ai_price_list"`
	AiLocationInfo   *string     `json:"ai_location_info"`
	AiContactChannel *string     `json:"ai_contact_channel"`
	AiExtraRules     *string     `json:"ai_extra_rules"`
	AiSystemPrompt   *string     `json:"ai_system_prompt"`
}

func (q *Queries) UpdatePagePersona(ctx context.Context, arg UpdatePagePersonaParams) (FacebookPage, error) {
	row := q.db.QueryRow(ctx, updatePagePersona,
		arg.ID,
		arg.AiRole,
		arg.AiIndustry,
		arg.AiTone,
		arg.AiPriceList,
		arg.AiLocationInfo,
		arg.AiContactChannel,
		arg.AiExtraRules,
		arg.AiSystemPrompt,
	)
	var i FacebookPage
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.PageName,
		&i.PageAccessToken,
		&i.Category,
		&i.IsActive,
		&i.PostingEnabled,
		&i.AiEnabled,
		&i.LastActiveAt,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiRole,
		&i.AiIndustry,
		&i.AiTone,
		&i.AiPriceList,
		&i.AiLocationInfo,
		&i.AiContactChannel,
		&i.AiExtraRules,
		&i.AiSystemPrompt,
		&i.AiPersonaID,
	)
	return i, err
}
