// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPostHistory = `-- name: InsertPostHistory :one
INSERT INTO facebook.post_history (
  post_id, page_id, content, image_url, media_urls, post_url,
  published_at, likes, comments, shares, reach, engagement_rate
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12
)
ON CONFLICT (post_id) DO UPDATE SET
  likes = EXCLUDED.likes,
  comments = EXCLUDED.comments,
  shares = EXCLUDED.shares,
  reach = EXCLUDED.reach,
  engagement_rate = EXCLUDED.engagement_rate
RETURNING id, post_id, page_id, content, image_url, media_urls, post_url,
          published_at, likes, comments, shares, reach, engagement_rate, created_at
`

type InsertPostHistoryParams struct {
	PostID         string             `json:"post_id"`
	PageID         pgtype.UUID        `json:"page_id"`
	Content        string             `json:"content"`
	ImageUrl       *string            `json:"image_url"`
	MediaUrls      []byte             `json:"media_urls"`
	PostUrl        *string            `json:"post_url"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Likes          int32              `json:"likes"`
	Comments       int32              `json:"comments"`
	Shares         int32              `json:"shares"`
	Reach          *int32             `json:"reach"`
	EngagementRate pgtype.Numeric     `json:"engagement_rate"`
}

// Records a successfully published post. UNIQUE on post_id (FB-side)
// means a duplicate webhook or worker retry cannot create two history
// rows for the same FB post.
func (q *Queries) InsertPostHistory(ctx context.Context, arg InsertPostHistoryParams) (FacebookPostHistory, error) {
	row := q.db.QueryRow(ctx, insertPostHistory,
		arg.PostID,
		arg.PageID,
		arg.Content,
		arg.ImageUrl,
		arg.MediaUrls,
		arg.PostUrl,
		arg.PublishedAt,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.Reach,
		arg.EngagementRate,
	)
	var i FacebookPostHistory
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.PostUrl,
		&i.PublishedAt,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Reach,
		&i.EngagementRate,
		&i.CreatedAt,
	)
	return i, err
}

const listPostHistory = `-- name: ListPostHistory :many
SELECT
  id, post_id, page_id, content, image_url, media_urls, post_url,
  published_at, likes, comments, shares, reach, engagement_rate, created_at
FROM facebook.post_history
ORDER BY published_at DESC
LIMIT $1
`

func (q *Queries) ListPostHistory(ctx context.Context, limit int32) ([]FacebookPostHistory, error) {
	rows, err := q.db.Query(ctx, listPostHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookPostHistory{}
	for rows.Next() {
		var i FacebookPostHistory
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PageID,
			&i.Content,
			&i.ImageUrl,
			&i.MediaUrls,
			&i.PostUrl,
			&i.PublishedAt,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.Reach,
			&i.EngagementRate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
