// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM facebook.content_queue WHERE id = $1
`

func (q *Queries) DeleteQueueItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQueueItem, id)
	return err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT
  id, page_id, content, image_url, media_urls, source, status,
  trend_id, prompt_template_id, created_at, updated_at
FROM facebook.content_queue
WHERE id = $1
`

func (q *Queries) GetQueueItem(ctx context.Context, id pgtype.UUID) (FacebookContentQueue, error) {
	row := q.db.QueryRow(ctx, getQueueItem, id)
	var i FacebookContentQueue
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Source,
		&i.Status,
		&i.TrendID,
		&i.PromptTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQueue = `-- name: ListQueue :many
SELECT
  id, page_id, content, image_url, media_urls, source, status,
  trend_id, prompt_template_id, created_at, updated_at
FROM facebook.content_queue
ORDER BY created_at DESC
`

func (q *Queries) ListQueue(ctx context.Context) ([]FacebookContentQueue, error) {
	rows, err := q.db.Query(ctx, listQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookContentQueue{}
	for rows.Next() {
		var i FacebookContentQueue
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Content,
			&i.ImageUrl,
			&i.MediaUrls,
			&i.Source,
			&i.Status,
			&i.TrendID,
			&i.PromptTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueueContent = `-- name: UpdateQueueContent :one
UPDATE facebook.content_queue
SET content = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, content, image_url, media_urls, source, status,
          trend_id, prompt_template_id, created_at, updated_at
`

type UpdateQueueContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

// Used by regenerate-content: replaces the body but keeps status.
func (q *Queries) UpdateQueueContent(ctx context.Context, arg UpdateQueueContentParams) (FacebookContentQueue, error) {
	row := q.db.QueryRow(ctx, updateQueueContent, arg.ID, arg.Content)
	var i FacebookContentQueue
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Source,
		&i.Status,
		&i.TrendID,
		&i.PromptTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQueueStatus = `-- name: UpdateQueueStatus :one
UPDATE facebook.content_queue
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, content, image_url, media_urls, source, status,
          trend_id, prompt_template_id, created_at, updated_at
`

type UpdateQueueStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) (FacebookContentQueue, error) {
	row := q.db.QueryRow(ctx, updateQueueStatus, arg.ID, arg.Status)
	var i FacebookContentQueue
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Source,
		&i.Status,
		&i.TrendID,
		&i.PromptTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
