// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repost.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO facebook.repost_campaigns (name, source_post_url, source_post_text, source_post_media_urls, caption_style, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, source_post_url, source_post_text, source_post_media_urls, caption_style, scheduled_at, status, created_at, started_at, completed_at, last_error
`

type CreateCampaignParams struct {
	Name                string             `json:"name"`
	SourcePostUrl       string             `json:"source_post_url"`
	SourcePostText      string             `json:"source_post_text"`
	SourcePostMediaUrls []byte             `json:"source_post_media_urls"`
	CaptionStyle        string             `json:"caption_style"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (FacebookRepostCampaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.SourcePostUrl,
		arg.SourcePostText,
		arg.SourcePostMediaUrls,
		arg.CaptionStyle,
		arg.ScheduledAt,
	)
	var i FacebookRepostCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourcePostUrl,
		&i.SourcePostText,
		&i.SourcePostMediaUrls,
		&i.CaptionStyle,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastError,
	)
	return i, err
}

const createCrawledPost = `-- name: CreateCrawledPost :one
INSERT INTO facebook.crawled_posts (page_id, source_url, fb_post_id, content, media_urls, video_urls, thumbnail_urls, full_picture, media_type, likes, comments, shares, reaction_icons, posted_at, permalink)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, page_id, source_url, fb_post_id, content, media_urls, media_type, likes, comments, shares, posted_at, permalink, is_selected, created_at, video_urls, thumbnail_urls, full_picture, reaction_icons
`

type CreateCrawledPostParams struct {
	PageID        string             `json:"page_id"`
	SourceUrl     string             `json:"source_url"`
	FbPostID      *string            `json:"fb_post_id"`
	Content       *string            `json:"content"`
	MediaUrls     []byte             `json:"media_urls"`
	VideoUrls     []byte             `json:"video_urls"`
	ThumbnailUrls []byte             `json:"thumbnail_urls"`
	FullPicture   string             `json:"full_picture"`
	MediaType     string             `json:"media_type"`
	Likes         int32              `json:"likes"`
	Comments      int32              `json:"comments"`
	Shares        int32              `json:"shares"`
	ReactionIcons []byte             `json:"reaction_icons"`
	PostedAt      pgtype.Timestamptz `json:"posted_at"`
	Permalink     *string            `json:"permalink"`
}

func (q *Queries) CreateCrawledPost(ctx context.Context, arg CreateCrawledPostParams) (FacebookCrawledPost, error) {
	row := q.db.QueryRow(ctx, createCrawledPost,
		arg.PageID,
		arg.SourceUrl,
		arg.FbPostID,
		arg.Content,
		arg.MediaUrls,
		arg.VideoUrls,
		arg.ThumbnailUrls,
		arg.FullPicture,
		arg.MediaType,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.ReactionIcons,
		arg.PostedAt,
		arg.Permalink,
	)
	var i FacebookCrawledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SourceUrl,
		&i.FbPostID,
		&i.Content,
		&i.MediaUrls,
		&i.MediaType,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.PostedAt,
		&i.Permalink,
		&i.IsSelected,
		&i.CreatedAt,
		&i.VideoUrls,
		&i.ThumbnailUrls,
		&i.FullPicture,
		&i.ReactionIcons,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO facebook.fb_groups (group_id, name, assigned_account_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, name, assigned_account_id, status, last_posted_at, created_at
`

type CreateGroupParams struct {
	GroupID           string      `json:"group_id"`
	Name              *string     `json:"name"`
	AssignedAccountID pgtype.UUID `json:"assigned_account_id"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (FacebookFbGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.GroupID,
		arg.Name,
		arg.AssignedAccountID,
		arg.Status,
	)
	var i FacebookFbGroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.AssignedAccountID,
		&i.Status,
		&i.LastPostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO facebook.repost_jobs (campaign_id, account_id, group_id, scheduled_at, anonymous_posting, auto_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, account_id, group_id, status, attempts, last_error, post_url, scheduled_at, anonymous_posting, auto_enabled, started_at, completed_at, created_at, updated_at
`

type CreateJobParams struct {
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	GroupID          string             `json:"group_id"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	AnonymousPosting bool               `json:"anonymous_posting"`
	AutoEnabled      bool               `json:"auto_enabled"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (FacebookRepostJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.CampaignID,
		arg.AccountID,
		arg.GroupID,
		arg.ScheduledAt,
		arg.AnonymousPosting,
		arg.AutoEnabled,
	)
	var i FacebookRepostJob
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AccountID,
		&i.GroupID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.PostUrl,
		&i.ScheduledAt,
		&i.AnonymousPosting,
		&i.AutoEnabled,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM facebook.repost_campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const deleteCrawledPostsForPage = `-- name: DeleteCrawledPostsForPage :exec
DELETE FROM facebook.crawled_posts WHERE page_id = $1
`

func (q *Queries) DeleteCrawledPostsForPage(ctx context.Context, pageID string) error {
	_, err := q.db.Exec(ctx, deleteCrawledPostsForPage, pageID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM facebook.fb_groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const disableAutoForAccountJobs = `-- name: DisableAutoForAccountJobs :exec
UPDATE facebook.repost_jobs
SET auto_enabled = false
WHERE account_id = $1 AND status != 'completed'
`

func (q *Queries) DisableAutoForAccountJobs(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableAutoForAccountJobs, accountID)
	return err
}

const enableAutoForAccountJobs = `-- name: EnableAutoForAccountJobs :exec
UPDATE facebook.repost_jobs
SET auto_enabled = true, anonymous_posting = $2,
    status = CASE WHEN status IN ('failed','expired') THEN 'pending' ELSE status END,
    last_error = CASE WHEN status IN ('failed','expired') THEN NULL ELSE last_error END,
    started_at = CASE WHEN status IN ('failed','expired') THEN NULL ELSE started_at END
WHERE account_id = $1 AND status != 'completed'
`

type EnableAutoForAccountJobsParams struct {
	AccountID        pgtype.UUID `json:"account_id"`
	AnonymousPosting bool        `json:"anonymous_posting"`
}

func (q *Queries) EnableAutoForAccountJobs(ctx context.Context, arg EnableAutoForAccountJobsParams) error {
	_, err := q.db.Exec(ctx, enableAutoForAccountJobs, arg.AccountID, arg.AnonymousPosting)
	return err
}

const expireOverdueCampaigns = `-- name: ExpireOverdueCampaigns :exec
UPDATE facebook.repost_campaigns
SET status = 'expired', last_error = 'Schedule expired: past due date'
WHERE status = 'pending' AND scheduled_at < $1
`

func (q *Queries) ExpireOverdueCampaigns(ctx context.Context, scheduledAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireOverdueCampaigns, scheduledAt)
	return err
}

const expireOverdueJobs = `-- name: ExpireOverdueJobs :exec
UPDATE facebook.repost_jobs
SET status = 'expired', last_error = 'Schedule expired: past due date'
WHERE status = 'pending' AND scheduled_at IS NOT NULL AND scheduled_at < $1
`

func (q *Queries) ExpireOverdueJobs(ctx context.Context, scheduledAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireOverdueJobs, scheduledAt)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, source_post_url, source_post_text, source_post_media_urls, caption_style, scheduled_at, status, created_at, started_at, completed_at, last_error FROM facebook.repost_campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id pgtype.UUID) (FacebookRepostCampaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i FacebookRepostCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourcePostUrl,
		&i.SourcePostText,
		&i.SourcePostMediaUrls,
		&i.CaptionStyle,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastError,
	)
	return i, err
}

const getDueCampaigns = `-- name: GetDueCampaigns :many
SELECT id, name, source_post_url, source_post_text, source_post_media_urls, caption_style, scheduled_at, status, created_at, started_at, completed_at, last_error FROM facebook.repost_campaigns
WHERE status = 'pending' AND scheduled_at <= $1 AND scheduled_at >= $2
ORDER BY scheduled_at ASC
`

type GetDueCampaignsParams struct {
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ScheduledAt_2 pgtype.Timestamptz `json:"scheduled_at_2"`
}

func (q *Queries) GetDueCampaigns(ctx context.Context, arg GetDueCampaignsParams) ([]FacebookRepostCampaign, error) {
	rows, err := q.db.Query(ctx, getDueCampaigns, arg.ScheduledAt, arg.ScheduledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookRepostCampaign{}
	for rows.Next() {
		var i FacebookRepostCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourcePostUrl,
			&i.SourcePostText,
			&i.SourcePostMediaUrls,
			&i.CaptionStyle,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, group_id, name, assigned_account_id, status, last_posted_at, created_at FROM facebook.fb_groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (FacebookFbGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i FacebookFbGroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.AssignedAccountID,
		&i.Status,
		&i.LastPostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGroups = `-- name: ListActiveGroups :many
SELECT id, group_id, name, assigned_account_id, status, last_posted_at, created_at FROM facebook.fb_groups WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListActiveGroups(ctx context.Context) ([]FacebookFbGroup, error) {
	rows, err := q.db.Query(ctx, listActiveGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookFbGroup{}
	for rows.Next() {
		var i FacebookFbGroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.AssignedAccountID,
			&i.Status,
			&i.LastPostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllJobs = `-- name: ListAllJobs :many
SELECT id, campaign_id, account_id, group_id, status, attempts, last_error, post_url, scheduled_at, anonymous_posting, auto_enabled, started_at, completed_at, created_at, updated_at FROM facebook.repost_jobs
WHERE ($1::text = '' OR status = $1)
  AND ($2::uuid IS NULL OR account_id = $2)
  AND ($3::text = '' OR group_id = $3)
ORDER BY updated_at DESC
LIMIT $4
`

type ListAllJobsParams struct {
	Column1 string      `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
}

// Queue view: paginate over every job across campaigns. Optional filters
// are applied via COALESCE-style NULL-tolerant WHERE clauses so a single
// query can serve the "Tất cả / Đang chờ / Theo account / Theo group"
// tabs in the plugin UI.
func (q *Queries) ListAllJobs(ctx context.Context, arg ListAllJobsParams) ([]FacebookRepostJob, error) {
	rows, err := q.db.Query(ctx, listAllJobs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookRepostJob{}
	for rows.Next() {
		var i FacebookRepostJob
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AccountID,
			&i.GroupID,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.PostUrl,
			&i.ScheduledAt,
			&i.AnonymousPosting,
			&i.AutoEnabled,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, source_post_url, source_post_text, source_post_media_urls, caption_style, scheduled_at, status, created_at, started_at, completed_at, last_error FROM facebook.repost_campaigns ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]FacebookRepostCampaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookRepostCampaign{}
	for rows.Next() {
		var i FacebookRepostCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourcePostUrl,
			&i.SourcePostText,
			&i.SourcePostMediaUrls,
			&i.CaptionStyle,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawledPostsForPage = `-- name: ListCrawledPostsForPage :many
SELECT id, page_id, source_url, fb_post_id, content, media_urls, media_type, likes, comments, shares, posted_at, permalink, is_selected, created_at, video_urls, thumbnail_urls, full_picture, reaction_icons FROM facebook.crawled_posts WHERE page_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCrawledPostsForPage(ctx context.Context, pageID string) ([]FacebookCrawledPost, error) {
	rows, err := q.db.Query(ctx, listCrawledPostsForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookCrawledPost{}
	for rows.Next() {
		var i FacebookCrawledPost
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.SourceUrl,
			&i.FbPostID,
			&i.Content,
			&i.MediaUrls,
			&i.MediaType,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.PostedAt,
			&i.Permalink,
			&i.IsSelected,
			&i.CreatedAt,
			&i.VideoUrls,
			&i.ThumbnailUrls,
			&i.FullPicture,
			&i.ReactionIcons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, group_id, name, assigned_account_id, status, last_posted_at, created_at FROM facebook.fb_groups ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]FacebookFbGroup, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookFbGroup{}
	for rows.Next() {
		var i FacebookFbGroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.AssignedAccountID,
			&i.Status,
			&i.LastPostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForCampaign = `-- name: ListJobsForCampaign :many
SELECT id, campaign_id, account_id, group_id, status, attempts, last_error, post_url, scheduled_at, anonymous_posting, auto_enabled, started_at, completed_at, created_at, updated_at FROM facebook.repost_jobs WHERE campaign_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListJobsForCampaign(ctx context.Context, campaignID pgtype.UUID) ([]FacebookRepostJob, error) {
	rows, err := q.db.Query(ctx, listJobsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookRepostJob{}
	for rows.Next() {
		var i FacebookRepostJob
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AccountID,
			&i.GroupID,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.PostUrl,
			&i.ScheduledAt,
			&i.AnonymousPosting,
			&i.AutoEnabled,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobsForCampaign = `-- name: ListPendingJobsForCampaign :many
SELECT id, campaign_id, account_id, group_id, status, attempts, last_error, post_url, scheduled_at, anonymous_posting, auto_enabled, started_at, completed_at, created_at, updated_at FROM facebook.repost_jobs WHERE campaign_id = $1 AND status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingJobsForCampaign(ctx context.Context, campaignID pgtype.UUID) ([]FacebookRepostJob, error) {
	rows, err := q.db.Query(ctx, listPendingJobsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookRepostJob{}
	for rows.Next() {
		var i FacebookRepostJob
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AccountID,
			&i.GroupID,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.PostUrl,
			&i.ScheduledAt,
			&i.AnonymousPosting,
			&i.AutoEnabled,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedCrawledPosts = `-- name: ListSelectedCrawledPosts :many
SELECT id, page_id, source_url, fb_post_id, content, media_urls, media_type, likes, comments, shares, posted_at, permalink, is_selected, created_at, video_urls, thumbnail_urls, full_picture, reaction_icons FROM facebook.crawled_posts WHERE page_id = $1 AND is_selected = true ORDER BY created_at DESC
`

func (q *Queries) ListSelectedCrawledPosts(ctx context.Context, pageID string) ([]FacebookCrawledPost, error) {
	rows, err := q.db.Query(ctx, listSelectedCrawledPosts, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookCrawledPost{}
	for rows.Next() {
		var i FacebookCrawledPost
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.SourceUrl,
			&i.FbPostID,
			&i.Content,
			&i.MediaUrls,
			&i.MediaType,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.PostedAt,
			&i.Permalink,
			&i.IsSelected,
			&i.CreatedAt,
			&i.VideoUrls,
			&i.ThumbnailUrls,
			&i.FullPicture,
			&i.ReactionIcons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleCampaign = `-- name: RescheduleCampaign :exec
UPDATE facebook.repost_campaigns
SET scheduled_at = $2, status = CASE WHEN status IN ('failed','expired') THEN 'pending' ELSE status END,
    started_at = NULL, completed_at = NULL, last_error = NULL
WHERE id = $1
`

type RescheduleCampaignParams struct {
	ID          pgtype.UUID        `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) RescheduleCampaign(ctx context.Context, arg RescheduleCampaignParams) error {
	_, err := q.db.Exec(ctx, rescheduleCampaign, arg.ID, arg.ScheduledAt)
	return err
}

const rescheduleJobsForCampaign = `-- name: RescheduleJobsForCampaign :exec
UPDATE facebook.repost_jobs
SET scheduled_at = $2, status = CASE WHEN status IN ('failed','running','expired') THEN 'pending' ELSE status END,
    last_error = CASE WHEN status IN ('failed','running','expired') THEN NULL ELSE last_error END,
    started_at = CASE WHEN status IN ('failed','running','expired') THEN NULL ELSE started_at END
WHERE campaign_id = $1 AND status != 'completed'
`

type RescheduleJobsForCampaignParams struct {
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) RescheduleJobsForCampaign(ctx context.Context, arg RescheduleJobsForCampaignParams) error {
	_, err := q.db.Exec(ctx, rescheduleJobsForCampaign, arg.CampaignID, arg.ScheduledAt)
	return err
}

const setCrawledPostSelected = `-- name: SetCrawledPostSelected :exec
UPDATE facebook.crawled_posts SET is_selected = $2 WHERE id = $1
`

type SetCrawledPostSelectedParams struct {
	ID         pgtype.UUID `json:"id"`
	IsSelected bool        `json:"is_selected"`
}

func (q *Queries) SetCrawledPostSelected(ctx context.Context, arg SetCrawledPostSelectedParams) error {
	_, err := q.db.Exec(ctx, setCrawledPostSelected, arg.ID, arg.IsSelected)
	return err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE facebook.repost_campaigns
SET status = $2, started_at = $3, completed_at = $4, last_error = $5
WHERE id = $1
`

type UpdateCampaignStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	LastError   *string            `json:"last_error"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LastError,
	)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE facebook.fb_groups SET name = $2, assigned_account_id = $3, status = $4, last_posted_at = $5 WHERE id = $1
`

type UpdateGroupParams struct {
	ID                pgtype.UUID        `json:"id"`
	Name              *string            `json:"name"`
	AssignedAccountID pgtype.UUID        `json:"assigned_account_id"`
	Status            string             `json:"status"`
	LastPostedAt      pgtype.Timestamptz `json:"last_posted_at"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.AssignedAccountID,
		arg.Status,
		arg.LastPostedAt,
	)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE facebook.repost_jobs
SET scheduled_at       = $2,
    auto_enabled       = $3,
    anonymous_posting  = $4,
    status             = CASE WHEN status IN ('failed','expired') THEN 'pending' ELSE status END,
    last_error         = CASE WHEN status IN ('failed','expired') THEN NULL ELSE last_error END,
    started_at         = CASE WHEN status IN ('failed','expired') THEN NULL ELSE started_at END,
    updated_at         = now()
WHERE id = $1
`

type UpdateJobParams struct {
	ID               pgtype.UUID        `json:"id"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	AutoEnabled      bool               `json:"auto_enabled"`
	AnonymousPosting bool               `json:"anonymous_posting"`
}

// Single-row update for the per-job edit modal: schedule time + flags.
// Bumps updated_at so the queue view's freshness index picks up the change.
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.Exec(ctx, updateJob,
		arg.ID,
		arg.ScheduledAt,
		arg.AutoEnabled,
		arg.AnonymousPosting,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE facebook.repost_jobs
SET status = $2, attempts = $3, last_error = $4, post_url = $5, started_at = $6, completed_at = $7
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	LastError   *string            `json:"last_error"`
	PostUrl     *string            `json:"post_url"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.PostUrl,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}
