// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSchedule = `-- name: CancelSchedule :one
UPDATE facebook.scheduled_posts
SET status = 'CANCELLED',
    updated_at = now()
WHERE id = $1 AND status = 'SCHEDULED'
RETURNING id, page_id, content, image_url, media_urls, status, scheduled_at,
          post_type, trend_reference, ai_generated, engagement_prediction,
          campaign_id, facebook_post_id, error_message, created_at, updated_at
`

func (q *Queries) CancelSchedule(ctx context.Context, id pgtype.UUID) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, cancelSchedule, id)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduled = `-- name: CreateScheduled :one
INSERT INTO facebook.scheduled_posts (
  page_id, content, image_url, media_urls, status, scheduled_at,
  post_type, trend_reference, ai_generated, engagement_prediction, campaign_id
) VALUES (
  $1, $2, $3, $4, 'SCHEDULED', $5,
  $6, $7, $8, $9, $10
)
RETURNING id, page_id, content, image_url, media_urls, status, scheduled_at,
          post_type, trend_reference, ai_generated, engagement_prediction,
          campaign_id, facebook_post_id, error_message, created_at, updated_at
`

type CreateScheduledParams struct {
	PageID               pgtype.UUID        `json:"page_id"`
	Content              string             `json:"content"`
	ImageUrl             *string            `json:"image_url"`
	MediaUrls            []byte             `json:"media_urls"`
	ScheduledAt          pgtype.Timestamptz `json:"scheduled_at"`
	PostType             string             `json:"post_type"`
	TrendReference       *string            `json:"trend_reference"`
	AiGenerated          bool               `json:"ai_generated"`
	EngagementPrediction []byte             `json:"engagement_prediction"`
	CampaignID           *string            `json:"campaign_id"`
}

func (q *Queries) CreateScheduled(ctx context.Context, arg CreateScheduledParams) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, createScheduled,
		arg.PageID,
		arg.Content,
		arg.ImageUrl,
		arg.MediaUrls,
		arg.ScheduledAt,
		arg.PostType,
		arg.TrendReference,
		arg.AiGenerated,
		arg.EngagementPrediction,
		arg.CampaignID,
	)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduled = `-- name: GetScheduled :one
SELECT
  id, page_id, content, image_url, media_urls, status, scheduled_at,
  post_type, trend_reference, ai_generated, engagement_prediction,
  campaign_id, facebook_post_id, error_message, created_at, updated_at
FROM facebook.scheduled_posts
WHERE id = $1
`

func (q *Queries) GetScheduled(ctx context.Context, id pgtype.UUID) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, getScheduled, id)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueScheduled = `-- name: ListDueScheduled :many
SELECT
  id, page_id, content, image_url, media_urls, status, scheduled_at,
  post_type, trend_reference, ai_generated, engagement_prediction,
  campaign_id, facebook_post_id, error_message, created_at, updated_at
FROM facebook.scheduled_posts
WHERE status = 'SCHEDULED' AND scheduled_at <= now()
ORDER BY scheduled_at ASC
LIMIT $1
`

// Worker query: returns up to N SCHEDULED rows whose scheduled_at is past.
// Returns 0..N rows; the worker then attempts to claim each via
// MarkSchedulePublishing (which acts as the lock).
func (q *Queries) ListDueScheduled(ctx context.Context, limit int32) ([]FacebookScheduledPost, error) {
	rows, err := q.db.Query(ctx, listDueScheduled, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookScheduledPost{}
	for rows.Next() {
		var i FacebookScheduledPost
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Content,
			&i.ImageUrl,
			&i.MediaUrls,
			&i.Status,
			&i.ScheduledAt,
			&i.PostType,
			&i.TrendReference,
			&i.AiGenerated,
			&i.EngagementPrediction,
			&i.CampaignID,
			&i.FacebookPostID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduled = `-- name: ListScheduled :many
SELECT
  id, page_id, content, image_url, media_urls, status, scheduled_at,
  post_type, trend_reference, ai_generated, engagement_prediction,
  campaign_id, facebook_post_id, error_message, created_at, updated_at
FROM facebook.scheduled_posts
ORDER BY scheduled_at ASC
`

func (q *Queries) ListScheduled(ctx context.Context) ([]FacebookScheduledPost, error) {
	rows, err := q.db.Query(ctx, listScheduled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookScheduledPost{}
	for rows.Next() {
		var i FacebookScheduledPost
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Content,
			&i.ImageUrl,
			&i.MediaUrls,
			&i.Status,
			&i.ScheduledAt,
			&i.PostType,
			&i.TrendReference,
			&i.AiGenerated,
			&i.EngagementPrediction,
			&i.CampaignID,
			&i.FacebookPostID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleFailed = `-- name: MarkScheduleFailed :one
UPDATE facebook.scheduled_posts
SET status = 'FAILED',
    error_message = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, content, image_url, media_urls, status, scheduled_at,
          post_type, trend_reference, ai_generated, engagement_prediction,
          campaign_id, facebook_post_id, error_message, created_at, updated_at
`

type MarkScheduleFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkScheduleFailed(ctx context.Context, arg MarkScheduleFailedParams) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, markScheduleFailed, arg.ID, arg.ErrorMessage)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSchedulePublished = `-- name: MarkSchedulePublished :one
UPDATE facebook.scheduled_posts
SET status = 'PUBLISHED',
    facebook_post_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, page_id, content, image_url, media_urls, status, scheduled_at,
          post_type, trend_reference, ai_generated, engagement_prediction,
          campaign_id, facebook_post_id, error_message, created_at, updated_at
`

type MarkSchedulePublishedParams struct {
	ID             pgtype.UUID `json:"id"`
	FacebookPostID *string     `json:"facebook_post_id"`
}

func (q *Queries) MarkSchedulePublished(ctx context.Context, arg MarkSchedulePublishedParams) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, markSchedulePublished, arg.ID, arg.FacebookPostID)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSchedulePublishing = `-- name: MarkSchedulePublishing :one
UPDATE facebook.scheduled_posts
SET status = 'PUBLISHING',
    updated_at = now()
WHERE id = $1 AND status = 'SCHEDULED'
RETURNING id, page_id, content, image_url, media_urls, status, scheduled_at,
          post_type, trend_reference, ai_generated, engagement_prediction,
          campaign_id, facebook_post_id, error_message, created_at, updated_at
`

// Atomic claim: only succeeds if status is still SCHEDULED.
// Used by the worker to prevent two workers picking the same row.
func (q *Queries) MarkSchedulePublishing(ctx context.Context, id pgtype.UUID) (FacebookScheduledPost, error) {
	row := q.db.QueryRow(ctx, markSchedulePublishing, id)
	var i FacebookScheduledPost
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Content,
		&i.ImageUrl,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PostType,
		&i.TrendReference,
		&i.AiGenerated,
		&i.EngagementPrediction,
		&i.CampaignID,
		&i.FacebookPostID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
