// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT
  id, event_type, facebook_entry_id, payload, signature, processed, processed_at, error_message, created_at
FROM facebook.webhook_events
WHERE id = $1
`

func (q *Queries) GetWebhookEvent(ctx context.Context, id pgtype.UUID) (FacebookWebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEvent, id)
	var i FacebookWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.FacebookEntryID,
		&i.Payload,
		&i.Signature,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO facebook.webhook_events (
  event_type, facebook_entry_id, payload, signature, processed, processed_at, error_message
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, event_type, facebook_entry_id, payload, signature, processed, processed_at, error_message, created_at
`

type InsertWebhookEventParams struct {
	EventType       string             `json:"event_type"`
	FacebookEntryID *string            `json:"facebook_entry_id"`
	Payload         json.RawMessage    `json:"payload"`
	Signature       *string            `json:"signature"`
	Processed       bool               `json:"processed"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage    *string            `json:"error_message"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (FacebookWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.EventType,
		arg.FacebookEntryID,
		arg.Payload,
		arg.Signature,
		arg.Processed,
		arg.ProcessedAt,
		arg.ErrorMessage,
	)
	var i FacebookWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.FacebookEntryID,
		&i.Payload,
		&i.Signature,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedWebhookEvents = `-- name: ListUnprocessedWebhookEvents :many
SELECT
  id, event_type, facebook_entry_id, payload, signature, processed, processed_at, error_message, created_at
FROM facebook.webhook_events
WHERE processed = false
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]FacebookWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacebookWebhookEvent{}
	for rows.Next() {
		var i FacebookWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.FacebookEntryID,
			&i.Payload,
			&i.Signature,
			&i.Processed,
			&i.ProcessedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE facebook.webhook_events
SET processed = true,
    processed_at = now(),
    error_message = $2
WHERE id = $1
`

type MarkWebhookProcessedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.ID, arg.ErrorMessage)
	return err
}
